```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-410-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-410-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1. completely agree; 2. somewhat agree; 3. somewhat disagree; 4. completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. Also included in the dataset are IQ scores, scale scores and the amount of alcohol use (1 = very often; 2 = often; 3 = sometimes; 4 = never).

To which of the 34 items do the adolescents give the most varied responses? (no decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-410-en-data.sav), [CSV file](eur-descriptive-410-en-data.csv)


Solution
========
The item with the most varied responses is item 16 (ask for descriptive statistics and look at the variances of all the items).


Meta-information
================
exname: eur-descriptive-410-en
extype: num
exsolution: 16
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Spread/Variance, Descriptive statistics/Summary Statistics/Measures of Spread/Standard Deviation
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
