```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-405-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-405-en-data.csv", recursive = TRUE)
```

Question
========
Een kennistest over alcohol bevat 20 items en wordt afgenomen bij 202 middelbare scholieren. De variabele total_score geeft de totale juiste scores. Geslacht (gender; 0 = vrouw; 1 = man) en alcoholgebruik (alchol_use; 0 = heel vaak; 1 = vaak; 2 = soms; 3 = nooit) zijn ook opgenomen in de dataset.

Wat is de totaalscore die overeenkomt met een percentielscore van 75% (geen decimalen)?

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-descriptive-405-en-data.sav), [CSV file](eur-descriptive-405-en-data.csv)


Solution
========
De totaalscore die overeenkomt met een percentielscore van 75% is 15.

Meta-information
================
exname: eur-descriptive-405-nl
extype: num
exsolution: 15
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[Type]: Performing analysis, Interpreting output
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
