```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-404-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-404-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. Also included in the dataset are IQ scores, scale scores and the amount of alcohol use (1 = very often; 2 = often; 3 = sometimes; 4 = never).

The researcher thinks that there is a difference in scale score between adolescents who drink a) very often, b) often,  c) sometimes, and d) never (variable [alcohol_use]). Conduct an Anova to investigate the difference in alcohol use among these four groups. What is the effect size (partial eta squared) of this effect? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-inferential_statistics-404-en-data.sav), [CSV file](eur-inferential_statistics-404-en-data.csv)


Solution
========
The effect size (partial eta squared) of the effect of alcohol use on the scale score is 0.411 (conduct an ANOVA using General Linear Model: Univariate and ask for estimates of effect size).


Meta-information
================
exname: eur-inferential_statistics-404-en
extype: num
exsolution: 0.411
extol: 0
exsection: Inferential Statistics/Effect size/Eta squared, Inferential Statistics/Parametric Techniques/ANOVA/Oneway ANOVA
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
