```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-140-nl-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-140-nl-data.csv", recursive = TRUE)
```

Question
========
Er is in het onderwijs veel aandacht voor de voordelen van PGO. Een onderzoeker aan de Erasmus Universiteit heeft op 4 meetmomenten informatie verzameld over de sociale vaardigheden van studenten. De studenten werden tijdens onderwijsgroepen geobserveerd en beoordeeld op sociale vaardigheid 1) 2 dagen na hun eerste PGO les [T1_social] ; 2) een half jaar na hun eerste PGO les [T2_social]; 3) een jaar na hun eerste PGO les [T3_social]; en 4) anderhalf jaar na hun eerste PGO les [T4_social]. Het sociale gedrag werd gescoord middels een semi-gestructureerd interview waarbij de scores kunnen variëren van 0 (niet sociaal) tot 40 (uiterst sociaal). Verder registreert de behandelaar of de patiënten last hebben van verlegenheid of niet [verlegen].

Open het databestand.

Voer eerst voor alle proefpersonen een analyse uit om te bepalen of de sociale vaardigheid verschilt voor de vier meetmomenten [T1_social, T2_social, T3_social, T4_social]. Wat is de F-waarde voor dit effect volgens de univariate benadering? (3 decimalen)

**Download**: [SPSS file](eur-inferential_statistics-140-nl-data.sav), [CSV file](eur-inferential_statistics-140-nl-data.csv)


Solution
========
De F-waarde is 521.962.


Meta-information
================
exname: eur-inferential_statistics-140-nl
extype: num
exsolution: 521.962
extol: 0
exsection: Inferential Statistics/Parametric Techniques/ANOVA/Oneway repeated measures ANOVA
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy