```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-411-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-411-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1. completely agree; 2. somewhat agree; 3. somewhat disagree; 4. completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. Also included in the dataset are IQ scores, scale scores and the amount of alcohol use (1 = very often; 2 = often; 3 = sometimes; 4 = never).

Calculate the percentile scores of the scale score (variable [scale]). What is the percentage of adolescents with a scale score of 23 or lower? Give the rounded percentage. (no decimals).

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-411-en-data.sav), [CSV file](eur-descriptive-411-en-data.csv)


Solution
========
The percentage of students with a scale score of 23 or lower is 8% (percentiles can be calculated using rank cases).


Meta-information
================
exname: eur-descriptive-411-en
extype: num
exsolution: 8
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[ID]: 9d540
exextra[Type]: Data manipulation, Interpreting output, Calculation
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
