
Question
========
Stel je bent als onderwijskundig onderzoeker geïnteresseerd in het effect van Kanjertraining op de afname van pestgedrag. Je voert hiervoor een experiment uit waarbij er op een vijftal scholen de Kanjertraining wordt aangeboden in 50 klassen. Daarnaast heb je gegevens verzameld bij vijf controlescholen met in totaal 35 klassen. Op de controlescholen wordt in geen van de klassen de Kanjertraining aangeboden. Het totaal aantal leerlingen dat bij het onderzoek is betrokken bedraagt ongeveer 1500. Bij de leerlingen zijn vragenlijsten afgenomen die de afname van pestgedrag meet op een interval schaal. 

Welke analysetechniek is het meest geschikt voor het beoordelen van het effect van de Kanjertraining op de afname van pestgedrag?

  
Answerlist
----------
* Meerweg ANOVA met pestgedrag als afhankelijke variabele.
* Meerweg ANCOVA met pestgedrag als factor.
* Mixed designanalyse met pestgedrag als factor.
# Multilevel analyse met pestgedrag als afhankelijke variabele.


Solution
========
  


Answerlist
----------



Meta-information
================
exname: uu-multilevel-analysis-800-nl.Rmd
extype: schoice
exsolution: 0001
exsection: Inferential Statistics/Multilevel Analysis
exextra[Type]: Test choice
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
