```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-237-nl-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-237-nl-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker twijfelt of hij toch niet beter atleet kan worden, en als hij daarvoor kiest, welke sport hij dan het beste kan kiezen. Om dit voor zichzelf te bepalen heeft hij een steekproef getrokken uit alle professionele sporters in de VS en bepaald wat hun gemiddelde jaarlijkse inkomen was (in 10.000 dollars). Daarnaast heeft hij bepaald wat voor sport [Voetbal = 1, Basketbal = 2, Honkbal = 3] iemand deed, en of het ging om een mannelijke [Geslacht = 0] of een vrouwelijke [Geslacht = 1] atleet.

Voer een gepaste test uit waarbij je sport en geslacht als onafhankelijke variabelen meeneemt en inkomen als afhankelijke variabele. Wat is de Sum of Squares voor de factor met het minst significante hoofdeffect? (3 decimalen)

**Download**: [SPSS file](eur-inferential_statistics-237-nl-data.sav), [CSV file](eur-inferential_statistics-237-nl-data.csv)


Solution
========
Het antwoord is 33.849.


Meta-information
================
exname: eur-inferential_statistics-237-nl
extype: num
exsolution: 33.849
extol: 0
exsection: Inferential Statistics/Parametric Techniques/ANOVA/Twoway ANOVA
exextra[ID]: bb7ac
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
