```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-402-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-402-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed a questionnaire with 12 items using Likert scales ranging from 1 (completely disagree) to 5 (completely agree). An example of an item is: When I go out, I often consume more than 5 alcoholic beverages. The answers of 608 adolescent girls (1) and boys (2) to the 12 items are in the dataset. Note: higher scores on the questionnaire reflect more alcohol abuse.

Calculate the total score by summing all the answers to all the items. Take the missings into account when calculating the total score and don’t include people who gave less than 8 answers. Make sure the total score is rounded. What is the mean of the total score? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-402-en-data.sav), [CSV file](eur-descriptive-402-en-data.csv)


Solution
========
The mean of the total score is 33.799. The total score is calculated using the mean.n and round function.


Meta-information
================
exname: eur-descriptive-402-en
extype: num
exsolution: 33.799
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[Type]: Data manipulation, Interpretating output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Thinking