```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-123-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-123-nl-data.csv", recursive = TRUE)
```

Question
========
* Nowledge about the professional field.*

A knowledge test about the professional field of psychologists and pedagogues consists of 20 items and was administered to 202 students in the master's program in psychology and pedagogy. The total number of correctly answered questions is shown in the variable [total score]. In addition, the scores (0 = not correct, 1 = correct) on item 8 from the above knowledge test are shown in the variable [item8].

Open the data file.

Based on the scores, identify a group consisting of those with a score of 12 or lower on the variable [total score]. What is the proportion correct of this group on item 8 (3 decimal places)?

* Download**: [SPSS file](eur-descriptive-123-nl-data.sav), [CSV file](eur-descriptive-123-nl-data.csv)


Solution
========
The proportion correct of this group on item 8 is .62. This means that 62% of the students in this group answered item 8 correctly.

Meta-information
================
exname: eur-descriptive-123-en
extype: num
exsolution: .62
extol: 0
exsection: Descriptive statistics/Summary Statistics/Proportion
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
