```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-245-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-245-en-data.csv", recursive = TRUE)
```
Question
========
Feyenoord and Ajax fans often criticize each other's teams. We will be looking at what team a person is a fan of [Fan, where Feyenoord = 0 and Ajax = 1], in what city a person lives [City, where Rotterdam = 1, Amsterdam = 2, Dordrecht = 3 and Haarlem = 4], the number of games played by the favourite team that they watched over the years (so the amount of games played by Feyenoord watched by a Feyenoord fan) [played_favourite] and to the amount of games played by the other team that someone watched over the years [played_other]. We also registered whose team became division champion in the last 4 years [Champion, where No championship = 0 and Championship = 1].

It is investigated whether the probability of winning the championship [Champion=1] is the same for all cities [City]. If the null hypothesis were true, what would be the expected number of fans from Rotterdam [City=1] that saw their team win a championship [Champion=1]? Report the expected number (using 1 decimal).

**Download**: [SPSS file](inferential_statistics-245-en-data.sav), [CSV file](inferential_statistics-245-en-data.csv)


Solution
========
The correct answer is 13.8


Meta-information
================
exname: eur-inferential_statistics-245-en
extype: num
exsolution: 13.8
extol: 0
exsection: Inferential Statistics/Parametric Techniques/Cross tables
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
