```{r, echo = FALSE, results = "hide"}
#Load package
library(knitr)
```

Question
========
In social science, researchers are interested in concepts that are not directly visible. After performing a factor analysis to extract the number of dimensions, it is common use to conduct a rotation. Generally, the researcher decides to do an ortogonal (varimax) or non-orthogonal (oblique) rotation to interpret the extracted dimensions. Why is a non‐orthogonal (oblique) rotation preferred over an orthogonal (varimax) rotation in most social science research?


Solution
========
Most theories in social science involve related constructs; therefore the factors measuring these constructs will be correlated. However, a varimax rotation would force the factors to be uncorrelated, twisting their meaning. Thus, the best option is an oblique rotation as it allows for factors to both be correlated or uncorrelated to each other, rather than forcing them to be fully uncorrelated.


Meta-information
================
exname: eur-factor-106-en
extype: string
exsolution: 
extol: 
exsection: Factor analysis/Rotations, Factor analysis/Exploratory factor analysis
exextra[Type]: Conceptual
exextra[Program]: 
exextra[Language]: English
exextra[Level]: Statistical Reasoning