```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-401-nl-data.sav", recursive = TRUE)
include_supplement("eur-reliability-401-nl-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker werkzaam bij het psychologie-instituut onderzoekt alcoholmisbruik onder adolescenten. De onderzoeker heeft een vragenlijst ontworpen met 12 items, waarbij gebruik wordt gemaakt van Likert-schalen variërend van 1 (helemaal mee oneens) tot 5 (helemaal mee eens). Een voorbeeld van een item is: Wanneer ik uitga, consumeer ik vaak meer dan 5 alcoholische drankjes. De antwoorden van 608 adolescente meisjes (1) en jongens (2) op de 12 items zijn opgenomen in de dataset. Let op: hogere scores op de vragenlijst duiden op meer alcoholmisbruik.

Voer een betrouwbaarheidsanalyse uit. Wat is de schaalvariantie wanneer alle items zijn opgenomen? (3 decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

**Download** [SPSS file](eur-reliability-401-nl-data.sav), [CSV file](eur-reliability-401-nl-data.csv)


Solution
========
De schaalvariantie wanneer alle items zijn opgenomen is 53.189 (vraag om schaalbeschrijvingen bij het uitvoeren van de betrouwbaarheidsanalyse).

Meta-information
================
exname: eur-reliability-401-nl
extype: num
exsolution: 53.189
extol: 0
exsection: Reliability/Descriptives, Reliability/Analysis/Cronbach's alpha
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
