```{r, echo = FALSE, results = "hide"}
include_supplement("eur-assumptions-103-nl-data.sav", recursive = TRUE)
include_supplement("eur-assumptions-103-nl-data.csv", recursive = TRUE)
```

Question
========
*Ter beschikking gesteld (TBS)*

Er is in Nederland momenteel veel discussie over het nut van langdurige opsluiting van TBS’ers. Een behandelaar van TBS kliniek de Kijvelanden heeft op 4 meetmomenten informatie verzameld over het agressieve gedrag van patiënten. De patiënten werden tijdens groepsbehandelingen geobserveerd en beoordeeld op agressief gedrag 1) 2 dagen na hun opname in de kliniek [T1_aggression]; 2) een half jaar na hun opname [T2_aggression]; 3) een jaar na hun opname [T3_aggression]; en 4) anderhalf jaar na hun opname [T4_aggression]. Het agressieve gedrag werd gescoord middels een semi-gestructureerd interview waarbij de scores kunnen variëren van 0 (niet agressief) tot 40 (uiterst agressief). Verder registreert de behandelaar of de patiënten last hebben van psychoses of niet [psychosis], waarbij 0 = geen psychose en 1 = psychose.

Open het databestand.

Toets of het gemiddelde niveau van agressief gedrag verschilt tussen de vier tijdstippen. Wat is de waarde van Greenhouse-Geisser Epsilon voor bovenstaand model? (3 decimalen)

**Download**: [SPSS file](eur-assumptions-103-nl-data.sav), [CSV file](eur-assumptions-103-nl-data.csv)

Solution
========
De Greenhouse-Geisser Epsilon is 0.935. De correcte analyse is repeated measures ANOVA, waarbij de Greenhouse-Geisser Epsilon wordt gebruikt om de aanname van sfericiteit te toetsen.

Meta-information
================
exname: eur-assumptions-103-nl
extype: num
exsolution: 0.935
extol: 0
exsection: Assumptions/Sphericity/Epsilon
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy