```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-406-en-data.sav", recursive = TRUE)
include_supplement("eur-factor-406-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. 

Conduct an unrotated explorative factor analysis with principal axis factoring on all the items of the questionnaire. What is the percentage of the variance that is explained by the second factor? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-factor-406-en-data.sav), [CSV file](eur-factor-406-en-data.csv)


Solution
========
The percentage of variance explained by the second factor is 7.129.


Meta-information
================
exname: eur-factor-406-en
extype: num
exsolution: 7.129
extol: 0
exsection: Factor analysis/Explained variance, Factor analysis/Exploratory factor analysis, Factor analysis/Eigenvalues
exextra[Type]: Interpretating output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy