```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-408-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-408-en-data.csv", recursive = TRUE)
```

Question
========
A knowledge test on alcohol contains 20 items and is administered to 202 high school students. The variable [total score] gives the total correct scores. Gender (0 = woman; 1 = man) and alcohol use (0 = very often; 1 = often; 2 = sometimes; 3 = never) are also included in the dataset. 

The researcher wants to assign the total scores of the students to the following percentile groups: 0-20% = 1; >20%-40% =2; >40%-60%=3; >60%-80%=4; >80% = 5. Compute a new variable indicating the percentile group that each student was assigned to based on their percentile scores. What is the proportion correct score (mean) on item 8  [item8] for the students assigned to percentile group 4? (2 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-408-en-data.sav), [CSV file](eur-descriptive-408-en-data.csv)


Solution
========
The proportion correct on item 8 for students assigned to percentile group 4 is 0.90. First a new variable has to be computed using the percentile scores and the recode into different variable function. After, find the mean of group 4 on item8. This mean represents the proportion correct on this item.


Meta-information
================
exname: eur-descriptive-408-en
extype: num
exsolution: 0.90
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean, Descriptive statistics/Summary Statistics/Proportion
exextra[Type]: Data manipulation, Interpretating output
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
