```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-110-nl-data.sav", recursive = TRUE)
include_supplement("eur-factor-110-nl-data.csv", recursive = TRUE)
```

Question
========
*Werk voor psychologen en pedagogen.*

Een wetenschapper doet onderzoek naar factoren die kunnen verklaren waarom de carriëremogelijkheden voor psychologen en pedagogen soms gering zijn. Vanuit theoretische inzichten over carriëremogelijkheden heeft de onderzoeker het idee dat er verschillende dimensies onderscheiden kunnen worden die iets te maken hebben met de carriëremogelijkheden. Ze heeft 34 stellingen bedacht waarop respondenten op een 4-puntsschaal (1. helemaal mee eens; 2. een beetje mee eens; 3. niet zo erg mee eens; 4. helemaal niet mee eens) aan kunnen geven of ze het eens zijn met een stelling. Een voorbeeld van een stelling is: “Ik heb tijdens mijn opleiding een relevante stage gelopen”. De vragenlijst is afgenomen bij 312 afgestudeerden. De responsen van de deelnemers op de 34 stellingen staan weergegeven in het databestand. 

Open het databestand.

Voer een factor analyse uit met principal axis factoring, waarbij 2 factoren worden geëxtraheerd en een varimax rotatie wordt uitgevoerd. Hoe hoog is voor deze analyse de correlatie tussen item 7 en factor 1? (3 decimalen)

**Download**: [SPSS file](eur-factor-110-nl-data.sav), [CSV file](eur-factor-110-nl-data.csv)


Solution
========
De correlatie tussen item 7 en de (geroteerde) factor 1 is 0.352. NB. Een factorlading is de correlatie tussen het item en de factor. Gegeven de opdracht gaan we uit van de geroteerde oplossing.


Meta-information
================
exname: eur-factor-110-nl
extype: num
exsolution: 0.352
extol: 0
exsection: Factor analysis/Structure matrix
exextra[ID]: 0b1bd
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
