```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-119-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-119-nl-data.csv", recursive = TRUE)
```


Question
========
*Kennis over het beroepsveld.*

Een kennistoets over het beroepsveld van psychologen en pedagogen bestaat uit 20 items en is afgenomen bij 202 studenten uit de master psychologie en pedagogiek. Het totale aantal correct beantwoorde vragen is weergegeven in de variabele [totaalscore]. 

Open het databestand.

Bereken de percentiel scores. Hoeveel procent van alle studenten heeft een totaalscore van 8 of lager? (1 decimaal).

**Download**: [SPSS file](eur-descriptive-119-nl-data.sav), [CSV file](eur-descriptive-119-nl-data.csv)



Solution
========
3.5% van de studenten heeft een totaalscore van 8 of lager.


Meta-information
================
exname: eur-descriptive-119-nl
extype: num
exsolution: 3.5
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[ID]: b5c86
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
