```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-402-nl-data.sav", recursive = TRUE)
include_supplement("eur-reliability-402-nl-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker van het instituut voor psychologie doet onderzoek naar alcoholmisbruik onder adolescenten. De onderzoeker ontwierp een vragenlijst met 12 items op Likert-schalen van 1 (helemaal mee oneens) tot 5 (helemaal mee eens). Een voorbeeld van een item is: Als ik uitga, drink ik vaak meer dan 5 alcoholische dranken. De antwoorden van 608 adolescente meisjes (1) en jongens (2) op de 12 items zitten in de dataset. Let op: hogere scores op de vragenlijst duiden op meer alcoholmisbruik.

Wat is de Spearman-Brown split-half betrouwbaarheid? (3 decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

**Download** [SPSS file](eur-reliability-402-nl-data.sav), [CSV file](eur-reliability-402-nl-data.csv)


Solution
========
De Spearman-Brown split-half betrouwbaarheid is 0,796.

Meta-information
================
exname: eur-reliability-402-nl
extype: num
exsolution: 0.796
extol: 0
exsection: Reliability/Analysis/Split half
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
