```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-406-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-406-en-data.csv", recursive = TRUE)
```

Question
========
Een kennistest over alcohol bevat 20 items en wordt afgenomen bij 202 middelbare scholieren. De variabele total_score geeft de totale juiste scores. Geslacht (gender; 0 = vrouw; 1 = man) en alcoholgebruik (alcohol_use; 0 = heel vaak; 1 = vaak; 2 = soms; 3 = nooit) zijn ook opgenomen in de dataset.

Wat is de kans op een totaalscore van 13,0 of lager onder de assumptie dat de scores afkomstig zijn van een normaal verdeelde populatie? (3 decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-descriptive-406-en-data.sav), [CSV file](eur-descriptive-406-en-data.csv)


Solution
========
De kans op een totaalscore van 13,0 of lager is 0,47 als we uitgaan van normaliteit (gebruik de functie cdf.normal om de p-waarden te berekenen en zoek dan de p-waarde op die hoort bij een score van 13).

Meta-information
================
exname: eur-descriptive-406-nl
extype: num
exsolution: 0.47
extol: 0
exsection: Descriptive statistics/Score interpretation/z-score, Distributions/Continuous/Normal
exextra[ID]: 088db
exextra[Type]: Data manipulation, Interpreting output
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
