```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-251-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-251-en-data.csv", recursive = TRUE)
```
Question
========
As you get older, going out becomes more of an exhaustion… the mind is willing, but the body is weak. To be able to advise the aging party-goers, a researcher drew a sample out of all the people visiting a certain nightclub in Rotterdam. The participants in the study were asked to report the amount of minutes they napped before going out and to report the amount of hours they spend partying that night. In addition, they had to fill in a questionnaire that quantified their natural need for sleep, and they needed to indicate whether their friends considered them to be a party-animal or a stay-at-home type of person [Group, where stay-at-home = 0 and party animal = 1]. 

If you want to know which independent variable (predictor) out of a set of two independent variables, measured on different scales [MinutesNap and Group], gives the best prediction of the amount of hours someone spent partying [HoursPartying], where do you need to look? Give the value of the relevant coefficient for the worst predictor. (3 decimals)

**Download**: [SPSS file](eur-inferential_statistics-251-en-data.sav), [CSV file](eur-inferential_statistics-251-en-data.csv)


Solution
========
The correct answer is 0.229.


Meta-information
================
exname: eur-inferential_statistics-251-en
extype: num
exsolution: 0.229
extol: 0
exsection: Inferential Statistics/Regression/Simple linear regression, Inferential Statistics/Regression/Standardized coefficient
exextra[ID]: 4973c
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
