```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-248-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-248-en-data.csv", recursive = TRUE)
```
Question
========
As you get older, going out becomes more of an exhaustion… the mind is willing, but the body is weak. To be able to advice the aging party-goers, a researcher drew a sample out of all the people visiting a certain nightclub in Rotterdam. The participants in the study were asked to report the amount of minutes they napped before going out and to report the amount of hours they spend partying that night. In addition, they had to fill in a questionnaire that quantified their natural need for sleep, and they needed to indicate whether their friends considered them to be a party-animal or a stay-at-home [Group, where stay-at-home = 0 and party animal = 1]. 

If you want to know the correlation between the amount of hours spent partying [HoursPartying] and the amount of minutes spent napping [MinutesNap], you need to use the Pearson correlation. Give the value of this correlation. (3 decimals)

**Download**: [SPSS file](eur-inferential_statistics-248-en-data.sav), [CSV file](eur-inferential_statistics-248-en-data.csv)


Solution
========
The correct answer is 0.075


Meta-information
================
exname: eur-inferential_statistics-248-en
extype: num
exsolution: 0.075
extol: 0
exsection: Inferential Statistics/Parametric Techniques/Correlations/Pearson
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
