```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-403-nl-data.sav", recursive = TRUE)
include_supplement("eur-reliability-403-nl-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker werkzaam bij het psychologie-instituut onderzoekt alcoholmisbruik onder adolescenten. De onderzoeker heeft een vragenlijst ontworpen met 12 items, waarbij gebruik wordt gemaakt van Likert-schalen variërend van 1 (helemaal mee oneens) tot 5 (helemaal mee eens). Een voorbeeld van een item is: Wanneer ik uitga, consumeer ik vaak meer dan 5 alcoholische drankjes. De antwoorden van 608 adolescente meisjes (1) en jongens (2) op de 12 items zijn opgenomen in de dataset. Let op: hogere scores op de vragenlijst duiden op meer alcoholmisbruik.

Eerder onderzoek heeft aangetoond dat jongens meer alcohol misbruiken dan meisjes. Vanwege deze bevinding wil een onderzoeker de betrouwbaarheid van de vragenlijst afzonderlijk voor jongens en meisjes berekenen (variabele [geslacht]). Wat is de betrouwbaarheid (Cronbach’s alpha) van de schaal voor de meisjes? (3 decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

**Download** [SPSS file](eur-reliability-403-nl-data.sav), [CSV file](eur-reliability-403-nl-data.csv)


Solution
========
De betrouwbaarheid (Cronbach’s alpha) van de schaal voor de meisjes is 0.780 (schakel de split file-optie in om subgroepen op basis van geslacht te maken voordat de analyse wordt uitgevoerd).

Meta-information
================
exname: eur-reliability-403-nl
extype: num
exsolution: 0.780
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
