```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-134-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-134-en-data.csv", recursive = TRUE)
```

Question
========
A researcher is interested in the influence of the drop in price for gasoline (bezine) on students who own a car. He wants to predict how many kilometers they will drive in in Januari 2015 [KM_JAN] by using a few predictors. For 202 students, the researcher has gathered the following data: 1) actual driven kilometers in Jan 2015 [KM_JAN], 2) actual driven kilometers in October 2014 [KM_OCT], 3) income for January 2015 [INCOME_JAN], 4) total kilometers traveled using public transport for February 2015 [PUB_TRANS], and 5) type of car [car] (1 = hybrid, 2 = sedan, 3 = suv).

Open the data file.

Predict the driven kilometers in January 2015 [KM_JAN] from the driven kilometers in October 2014 [KM_OCT], income for January 2015 [INCOME_JAN] and total kilometers traveled using public transport for February 2015 [PUB_TRANS]. What is the explained variance for this model (in the sample)? (3 decimals)

**Download**: [SPSS file](eur-inferential_statistics-134-en-data.sav), [CSV file](eur-inferential_statistics-134-en-data.csv)


Solution
========
The proportion explained variance is 0.500.


Meta-information
================
exname: eur-inferential_statistics-134-en
extype: num
exsolution: 0.500
extol: 0
exsection: Inferential Statistics/Regression/R squared
exextra[ID]: 1f115
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
