```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-408-en-data.sav", recursive = TRUE)
include_supplement("eur-factor-408-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. 

Conduct a factor analysis with principal axis factoring with 2 factors and an orthogonal varimax rotation, what is the correlation between factor 2 and item 3 on the rotated factor matrix? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-factor-408-en-data.sav), [CSV file](eur-factor-408-en-data.csv)


Solution
========
The correlation between factor 2 and item 3 after varimax rotation is 0.062 (see the rotated factor matrix for the factor loading of item 3 on factor 2).


Meta-information
================
exname: eur-factor-408-en
extype: num
exsolution: 0.062
extol: 0
exsection: Factor analysis/Exploratory factor analysis, Factor analysis/Rotations, Factor analysis/Factor loadings
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy