```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
A test consisting of 10 items has an alpha estimate of reliability of .50. How many parallel items have to be added to get an alpha estimate of reliability of .80?

Use $n =\frac{R_{xx-revised}(1-R_{xx-original})}{R_{xx-original}(1-R_{xx-revised})}$ in which n is the factor with which the original number of items has to be multiplied


Solution
========
In order to calculate the number of items that have to be added we need the Spearman Brown formula: 
$n = \frac{R_{xx-revised}(1-R_{xx-original})}{R_{xx-original}(1-R_{xx-revised})}$ in which n is the factor with which the original number of items has to be multiplied. So in our case:
$n = \frac{.8(1-.5)}{.5(1-.8)} = \frac{.4}{.1} = 4$. The number of items that has to be added is $40 ‐ 10 = 30$.


Meta-information
================
exname: eur-reliability-111-en
extype: num
exsolution: 30
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[Type]: Calculate
exextra[Program]: Calculator
exextra[Language]: English
exextra[Level]: Statistical Literacy
