```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-127-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-127-en-data.csv", recursive = TRUE)
```

Question
========
Open the SPSS file.

An error has been made in the calculation of the course exam of course 2.2 (variable course 2_2). The grade of each student has to be recalculated by adding 0.2 points to the current score. Please do this recalculation and report the mean for the new grades of course 2.2. Please note that for some students the new course exam score is higher than 10. You do not need to correct for that in the calculation of the mean. Round your answer to 4 decimal places.


**Download**: [SPSS file](eur-descriptive-127-en-data.sav), [CSV file](eur-descriptive-127-en-data.csv)


Solution
========
The mean for the new grades of course 2.2 is 5.3741.


Meta-information
================
exname: eur-descriptive-127-en
extype: num
exsolution: 5.3741
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[ID]: 5630d
exextra[Type]: Calculation
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
