```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-207-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-207-nl-data.csv", recursive = TRUE)
```


Question
========
Wat is het gemiddelde cijfer voor het tentamen inleiding in de sociologie (variabele: inleiding_sociologie) voor de studenten die op het tentamen van methodenleer (variabele: methodenleer) een onvoldoende (score lager dan 5.5) hebben gehaald en die een score van 1 hadden op stelling 2 (variabele: stelling2)? Schrijf je antwoord in het antwoordvakje (met 3 cijfers achter de komma).

**Download**: [SPSS file](eur-descriptive-207-nl-data.sav), [CSV file](eur-descriptive-207-nl-data.csv)


Solution
========
Het correcte antwoord is 3.599.


Meta-information
================
exname: eur-descriptive-207-nl
extype: num
exsolution: 3.599
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[Type]: Calculation
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
