```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-401-en-data.sav", recursive = TRUE)
include_supplement("eur-reliability-401-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed a questionnaire with 12 items using Likert scales ranging from 1 (completely disagree) to 5 (completely agree). An example of an item is: When I go out, I often consume more than 5 alcoholic beverages. The answers of 608 adolescent girls (1) and boys (2) to the 12 items are in the dataset. Note: higher scores on the questionnaire reflect more alcohol abuse.

Conduct a reliability analysis. What is the scale variance when all the items are included? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-reliability-401-en-data.sav), [CSV file](eur-reliability-401-en-data.csv)


Solution
========
The scale variance when all items are included is 53.189 (ask for scale descriptives when conducting the reliability analysis).


Meta-information
================
exname: eur-reliability-401-en
extype: num
exsolution: 53.189
extol: 0
exsection: Reliability/Descriptives, Reliability/Analysis/Cronbach's alpha
exextra[ID]: 5e55c
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
