```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-121-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-121-nl-data.csv", recursive = TRUE)
```


Question
========
*Knowledge about the professional field.*

A knowledge test about the professional field of psychologists and pedagogues consists of 20 items and was administered to 202 students in the master's degree program in psychology and pedagogy. The total number of correctly answered questions is shown in the variable [total score].

Open the data file.

What is the total score associated with a percentile score of 75%? (no decimal places)

* Download**: [SPSS file](eur-descriptive-121-nl-data.sav), [CSV file](eur-descriptive-121-nl-data.csv)

Solution
========
The total score associated with a percentiesl score of 75% is 15.

Meta-information
================
exname: eur-descriptive-121-en
extype: num
exsolution: 15
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
