```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
The “Three Minutes Test” (TMT) is a test to assess technical reading level. Children have to accurately read as many words as possible during three minutes. A teacher from grade 5 wants to use the test, which was constructed for children in grade 2, to assess the reading skills of her grade 5 children.
Cronbach’s alpha based on the grade 2 population is .88 and the standard deviation of the test scores in grade 2 is 3.

Explain why the TMT will probably be less reliably for the children in grade 5.


Solution
========
The TMT will probably be less reliably for the children in grade 5 because the variation in true scores is expected to be smaller. Since it is assumed from classical test theory that the error variance is equal for children in grade 2 and grade 4, the reliability will be lower in a population with less true score variance.


Meta-information
================
exname: eur-reliability-113-en
extype: string
exsolution: ""
extol: 
exsection: Reliability/Analysis/Cronbach's alpha
exextra[ID]: 30a03
exextra[Type]: Conceptual
exextra[Program]: 
exextra[Language]: English
exextra[Level]: Statistical Reasoning
