```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-122-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-122-nl-data.csv", recursive = TRUE)
```

Question
========
*Knowledge about the professional field.*

A knowledge test about the professional field of psychologists and pedagogues consists of 20 items and was administered to 202 students in the master's program in psychology and pedagogy. The total number of correctly answered questions is shown in the variable [total score]. In addition, the scores (0 = not correct, 1 = correct) on item 8 from the above knowledge test are shown in the variable [item8].

Open the data file.

The researcher would like to divide the student's total scores into the following 2 percentile groups: 0-85% = 1; and >85% = 2. Create a new variable in which each student is assigned to the correct percentile group based on his or her percentile score for the variable [total score]. What is the proportion correct on item 8 [item8] for students belonging to percentile group 2? (2 decimal places)

* Download**: [SPSS file](eur-descriptive-122-nl-data.sav), [CSV file](eur-descriptive-122-nl-data.csv)


Solution
========
The proportion correct on item 8 for students belonging to percentile group 2 is .82. This means that 82% of students in this group answered item 8 correctly.

Meta-information
================
exname: eur-descriptive-122-en
extype: num
exsolution: .82
extol: 0
exsection: Descriptive statistics/Summary Statistics/Proportion
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
