```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-401-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-401-en-data.csv", recursive = TRUE)
```

Question
========
A knowledge test on alcohol contains 20 items and is administered to 202 high school students. The variable [total score] gives the total correct scores. Gender (0 = woman; 1 = man) and alcohol use (0 = very often; 1 = often; 2 = sometimes; 3 = never) are also included in the dataset. 

A researcher wants to investigate whether he can predict the total score with an IQ score and wonders whether this relation is different for boys and girls. Conduct a regression analysis to investigate this question. What is the unstandardized regression coefficient of the interaction effect gender x IQ score? Note: Make sure that gender is coded as 0 for the girls and 1 for the boys. (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-inferential_statistics-401-en-data.sav), [CSV file](eur-inferential_statistics-401-en-data.csv)


Solution
========
The unstandardized coefficient for the interaction effect (gender x IQ) is -0.096. First compute an interaction variable (gender*IQ). Then use regression to predict the total score with gender, IQ and the interaction as the predictors. Finally find the coefficient for the interaction effect.


Meta-information
================
exname: eur-inferential_statistics-401-en
extype: num
exsolution: -0.096
extol: 0
exsection: Inferential Statistics/Regression/Slope, Inferential Statistics/Regression/Simple linear regression
exextra[ID]: 5ea1c
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
