```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-401-en-data.sav", recursive = TRUE)
include_supplement("eur-factor-401-en-data.csv", recursive = TRUE)
```

Question
========
A researcher investigates the factors that may explain alcohol abuse among the elderly. Based on his theory, the researcher suspects that different dimensions can be distinguished concerning alcohol abuse. She designed 34 statements the elderly can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The questionnaire was administered to 312 elderly (>70 years). The responses of the participants to the 34 statements are given in the dataset.

Conduct an unrotated explorative factor analysis with principal axis factoring on all the items of the questionnaire. What is the percentage of the variance that is explained by the third factor? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-factor-401-en-data.sav), [CSV file](eur-factor-401-en-data.csv)


Solution
========
The percentage of variance explained by the third factor is 6.658.


Meta-information
================
exname: eur-factor-401-en
extype: num
exsolution: 6.658
extol: 0
exsection: Factor analysis/Explained variance, Factor analysis/Eigenvalues, Factor analysis/Exploratory factor analysis
exextra[ID]: bb169
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
