```{r, echo = FALSE, results = "hide"}
include_supplement("eur-assumptions-106-nl-data.sav", recursive = TRUE)
include_supplement("eur-assumptions-106-nl-data.csv", recursive = TRUE)
```

Question
========
*Sociale vaardigheden en Probleem Gestuurd Onderwijs (PGO)*

Er is in het onderwijs veel aandacht voor de voordelen van PGO. Een onderzoeker aan de Erasmus Universiteit heeft op 4 meetmomenten informatie verzameld over de sociale vaardigheden van studenten. De studenten werden tijdens onderwijsgroepen geobserveerd en beoordeeld op sociale vaardigheid 1) 2 dagen na hun eerste PGO les [T1_social] ; 2) een half jaar na hun eerste PGO les [T2_social]; 3) een jaar na hun eerste PGO les [T3_social]; en 4) anderhalf jaar na hun eerste PGO les [T4_social]. Het sociale gedrag werd gescoord middels een semi-gestructureerd interview waarbij de scores kunnen variëren van 0 (niet sociaal) tot 40 (uiterst sociaal). Verder registreert de behandelaar of de patiënten last hebben van verlegenheid of niet [verlegen].

Open het databestand.

Toets of het gemiddelde niveau van sociale vaardigheden verschilt tussen de vier tijdstippen. Wat is de waarde van Greenhouse-Geisser Epsilon voor bovenstaand model? (3 decimalen)

**Download**: [SPSS file](eur-assumptions-106-nl-data.sav), [CSV file](eur-assumptions-106-nl-data.csv)

Solution
========
De Greenhouse-Geisser Epsilon is 0.935. De correcte analyse is repeated measures ANOVA, waarbij de Greenhouse-Geisser Epsilon wordt gebruikt om de aanname van sfericiteit te toetsen.

Meta-information
================
exname: eur-assumptions-106-nl
extype: num
exsolution: 0.935
extol: 0
exsection: Assumptions/Sphericity/Epsilon
exextra[ID]: 2490c
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
