```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-263-nl-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-263-nl-data.csv", recursive = TRUE)
```

Question
========
Een docent vraagt zich af of het gemiddelde cijfer voor logica (variabele logica) voor uitwonende studenten [Woon = 0] afwijkt van het gemiddelde voor thuiswonende [Woon = 1] studenten. Voer de analyse uit en geef de p-waarde van de Levene's Test (met 3 cijfers achter de komma).  

**Download**: [SPSS file](eur-inferential_statistics-263-nl-data.sav), [CSV file](eur-inferential_statistics-263-nl-data.csv)


Solution
========
Het correcte antwoord is 0.219


Meta-information
================
exname: eur-inferential_statistics-263-nl
extype: num
exsolution: 0.219
extol: 0
exsection: Assumptions/Homogeneity of variance/Levene's test, Inferential Statistics/Parametric Techniques/t-test/Independent samples means
exextra[ID]: ebcf8
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
