```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-409-en-data.sav", recursive = TRUE)
include_supplement("eur-factor-409-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. 

Conduct a factor analysis with principal axis factoring with 3 factors and a non-orthogonal promax rotation. What is the value of the coefficient that shows the unique contribution of factor 2 on item 9? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-factor-409-en-data.sav), [CSV file](eur-factor-409-en-data.csv)


Solution
========
The value of the coefficient that shows the unique contribution of factor 2 on item 9 is -0.065 (see the pattern matrix for the unique contributions between the factors and items).


Meta-information
================
exname: eur-factor-409-en
extype: num
exsolution: -0.065
extol: 0
exsection: Factor analysis/Pattern matrix, Factor analysis/Exploratory factor analysis, Factor analysis/Rotations
exextra[Type]: Interpretating output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy