```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-406-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-406-en-data.csv", recursive = TRUE)
```

Question
========
A knowledge test on alcohol contains 20 items and is administered to 202 high school students. The variable [total score] gives the total correct scores. Gender (0 = woman; 1 = man) and alcohol use (0 = very often; 1 = often; 2 = sometimes; 3 = never) are also included in the dataset. 

What is the probability of a total score of 13.0 or lower under the assumption that the scores come from a normally distributed population? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-406-en-data.sav), [CSV file](eur-descriptive-406-en-data.csv)


Solution
========
The probability of a total score of 13.0 or lower is 0.47 when we assume normality (use the cdf.normal function to calculate the p-values and then look up the p-value associated with a score of 13).


Meta-information
================
exname: eur-descriptive-406-en
extype: num
exsolution: 0.47
extol: 0
exsection: Descriptive statistics/Score interpretation/z-score, Distributions/Continuous/Normal
exextra[Type]: Data manipulation, Interpreting output
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
