```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-112-nl-data.sav", recursive = TRUE)
include_supplement("eur-factor-112-nl-data.csv", recursive = TRUE)
```

Question
========
* Ork for psychologists and educators.*

A scientist is investigating factors that may explain why career opportunities for psychologists and educators are sometimes low. From theoretical insights about career opportunities, the researcher has the idea that several dimensions can be distinguished that have something to do with career opportunities. She has devised 34 statements on which respondents can indicate whether they agree with a statement on a 4-point scale (1. completely agree; 2. somewhat agree; 3. not so much agree; 4. not at all agree). An example of a statement is, "I completed a relevant internship during my education." The questionnaire was administered to 312 graduates. Participants' responses to the 34 statements are shown in the data file.

Open the data file.

Perform a factor analysis with principal axis factoring, extracting 2 factors and performing a promax rotation. How high is the correlation between factor 1 and 2? (3 decimal places)

* Download**: [SPSS file](eur-factor-112-nl-data.sav), [CSV file](eur-factor-112-nl-data.csv)


Solution
========
The correlation between factor 1 and 2 after promax rotation in a 2-factor solution is -0.023.

Meta-information
================
exname: eur-factor-112-en
extype: num
exsolution: -0.023
extol: 0
exsection: Factor analysis/Factor correlation matrix
exextra[ID]: 0aabb
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
