```{r, echo = FALSE, results = "hide"}
include_supplement("eur-assumptions-106-en-data.sav", recursive = TRUE)
include_supplement("eur-assumptions-106-en-data.csv", recursive = TRUE)
```

Question
========
*Social skills and Problem Based Learning (PBL)*

A researcher from Erasmus University Rotterdam is investigating the possible advantages of PBL on students’ social competencies and has gathered social competency scores about students on four occasions. These scores come from observations by the researcher 2 days after their first PBL group (T1_social), six months after their first PBL tutor group (T2­_social), a year after their first PBL tutor group (T3_social) and a year and a half after their first PBL tutor group (T4_social). At these four occasions, social competence was measured using a semi-structured interview with scores varying from 0 (not social) to 40 (very social). Additionally, the researcher determines whether a student is shy or not [SHY]. 

Open the data file.

Test whether the mean level of social compentency differs between the four points in time. What is the value of Greenhouse-Geisser Epsilon for this model? (3 decimals)

**Download**: [SPSS file](eur-assumptions-106-en-data.sav), [CSV file](eur-assumptions-106-en-data.csv)

Solution
========
Greenhouse-Geisser Epsilon is 0.935. The correct analysis is repeated measures ANOVA, where the Greenhouse-Geisser Epsilon is used to test the sphericity assumption.

Meta-information
================
exname: eur-assumptions-106-en
extype: num
exsolution: 0.935
extol: 0
exsection: Assumptions/Sphericity/Epsilon
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy