```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-219-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-219-nl-data.csv", recursive = TRUE)
```

Question
========
A survey was conducted among economics students at EUR on students' attitudes toward macroeconomics (variable: macro_economics). Thesis 1 was "macroeconomics is useful in the context of this study." This statement had to be answered on a 7-point Likert scale, where 1 = completely disagree and 7 = completely agree. What percentage of students gave a score of 7 (completely agree)? Write the percentage (with 1 decimal place) in the answer box.

* Download**: [SPSS file](eur-descriptive-219-nl-data.sav), [CSV file](eur-descriptive-219-nl-data.csv)


Solution
========
The correct answer is 13.6.

Meta-information
================
exname: eur-descriptive-219-en
extype: num
exsolution: 13.6
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile, Descriptive statistics/Summary Statistics/Proportion
exextra[Type]: Calculation
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
