```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-403-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-403-en-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker van het instituut voor psychologie doet onderzoek naar alcoholmisbruik onder adolescenten. De onderzoeker ontwierp 34 stellingen waar de adolescenten het mee eens of oneens kunnen zijn op een vierpuntsschaal (1 = helemaal mee eens; 2 = enigszins mee eens; 3 = enigszins mee oneens; 4 = helemaal mee oneens). Een voorbeeld van een stelling is: Als ik me eenzaam voel, drink ik graag een alcoholische drank. De antwoorden van 312 meisjes (0) en jongens (1) op de 34 stellingen zitten in de dataset. Ook IQ-scores, schaalscores en de hoeveelheid alcoholgebruik (1 = heel vaak; 2 = vaak; 3 = soms; 4 = nooit) zijn in de dataset opgenomen.

De onderzoeker wil onderzoeken of hij de schaalscore kan voorspellen met IQ (variabele [IQ]) en vraagt zich af of deze relatie verschillend is voor jongens en meisjes. Voer een regressieanalyse uit om deze vraag te onderzoeken. Wat is de standaardfout van de regressiecoëfficiënt van het interactie-effect geslacht x IQ? (3 decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-inferential_statistics-403-en-data.sav), [CSV file](eur-inferential_statistics-403-en-data.csv)


Solution
========
De standaardafwijking van de regressiecoëfficiënt voor het interactie-effect (geslacht x IQ) is 0,014. Bereken eerst een interactievariabele (geslacht*IQ). Gebruik dan regressie om de schaalscore te voorspellen met geslacht, IQ en de interactie als voorspellers. Vind tenslotte de standaardfout voor het interactie-effect.

Meta-information
================
exname: eur-inferential_statistics-403-nl
extype: num
exsolution: 0.014
extol: 0
exsection: Inferential Statistics/Regression/Slope, Inferential Statistics/Regression/Simple linear regression
exextra[ID]: b3033
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
