```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-233-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-233-en-data.csv", recursive = TRUE)
```

Question
========
A question that has puzzled researchers for years is...do you really sleep worse after watching a horror movie? To answer this question once and for all, a researcher at EUR drew a sample from all visitors to a Horror-film festival (Slasher-fest) in Rotterdam.  The participants had to indicate the length of the movie they had watched at the festival, and how many hours they had slept the night after the festival. The researcher also administered a questionnaire to the participants measuring their "degree of anxiety," and recorded whether a person was male [Gender = 0] or female [Gender = 1].

Add the variable Anxiety Score to the model that initially included only MinutenFilm as a predictor. What is the difference in proportion explained variance compared to the model with only MinutenFilm? (3 decimal places)

* Download**: [SPSS file](eur-inferential_statistics-233-en-data.sav), [CSV file](eur-inferential_statistics-233-en-data.csv)


Solution
========
The correct answer is 0.125

Meta-information
================
exname: eur-inferential_statistics-233-en
extype: num
exsolution: 0.125
extol: 0
exsection: Inferential Statistics/Regression/Simple linear regression, Inferential Statistics/Regression/R squared, Inferential Statistics/Regression/Multiple linear regression/R squared change
exextra[ID]: 15a60
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
