```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
Hoe is het mogelijk dat, hoewel alfa een ondergrens stelt aan de grootte van de geschatte betrouwbaarheid, het in de praktijk mogelijk is om een alfa te krijgen die hoger is dan de werkelijke betrouwbaarheid?


Solution
========
Het is mogelijk dat, hoewel alfa een ondergrens stelt aan de grootte van de geschatte betrouwbaarheid, men in de praktijk een alfa krijgt die hoger is dan de werkelijke betrouwbaarheid. Dit komt doordat de alfa wordt berekend op basis van een steekproef en niet op basis van de volledige populatie. De alfa van de steekproef kan dus groot zijn (zelfs groter dan de werkelijke betrouwbaarheid). $r_{xx'}$) als gevolg van variabiliteit in de bemonstering.

Meta-information
================
exname: eur-reliability-108-nl
extype: string
exsolution: ""
extol: 
exsection: Reliability/Analysis/Cronbach's alpha
exextra[ID]: 75089
exextra[Type]: Conceptual
exextra[Program]: 
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
