```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-122-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-122-en-data.csv", recursive = TRUE)
```

Question
========
A researcher is interested in the consequences of the 2008 financial crisis for 16- and 17-year olds. She wants to predict their leisure expenses in November 2012 [expenses_nov] from a number of predictors. She collected data from 202 teenagers: 1) leisure expenses in November 2012 [expenses_nov]; 2) leisure expenses in July 2012 [expenses_jul]; 3) income from their side occupation in November 2012 [salary_nov]; 4) time spent on studying [studytime]; and 5) their educational level [education] (1 = vmbo, 2 = havo, 3 = vwo)*.

**translation for the Dutch education levels: (1 = Lower General Secondary Education, 2 = Higher General Secondary Education, 3 = Pre-university Education)*


Open the data file.

Predict leisure expenses in November 2012 [expenses_nov] from leisure expenses in July 2012 [expenses_jul], income from their side occupation in November 2012 [salary_nov], and time spent on studying [studytime]. What is proportion explained variance of this model (in the sample)? (3 decimals)

**Download**: [SPSS file](eur-inferential_statistics-122-en-data.sav), [CSV file](eur-inferential_statistics-122-en-data.csv)


Solution
========
The proportion explained variance is 0.500.


Meta-information
================
exname: eur-inferential_statistics-122-en
extype: num
exsolution: 0.500
extol: 0
exsection: Inferential Statistics/Regression/R squared
exextra[ID]: 95c73
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
