```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-226-nl-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-226-nl-data.csv", recursive = TRUE)
```

Question
========
Mannen en vrouwen hebben in de auto vaak commentaar op elkaars rijgedrag. We kijken naar het geslacht van wie er achter het stuur zit [Chauffeur, waarbij man = 0, vrouw = 1], in welk merk auto iemand rijdt [Auto, waarbij Ford = 1, Audi = 2, Toyota = 3, en Volkswagen = 4], naar de gereden kilometers [Gereden_kilometers] en naar de kilometers als bijrijder [Bijrijder_kilometers]. Ook kijken we naar wie een botsing heeft gekregen en wie niet [Botsing, waarbij geen botsing = 0, wel botsing = 1].

Er wordt onderzocht of de kans op het krijgen van een botsing [Botsing] procentueel hetzelfde is voor alle vier automerken [Auto]. Als de nulhypothese in dit onderzoek waar zou zijn, wat is dan de verwachte waarde van het aantal Ford-rijders dat een botsing krijgt? Schrijf het verwachte aantal in het antwoordvakje (met 1 cijfer achter de komma).

**Download**: [SPSS file](eur-inferential_statistics-226-nl-data.sav), [CSV file](eur-inferential_statistics-226-nl-data.csv)


Solution
========
Het correcte antwoord is 13.8.


Meta-information
================
exname: eur-inferential_statistics-226-nl
extype: num
exsolution: 13.8
extol: 0
exsection: Inferential Statistics/Parametric Techniques/Cross tables, Inferential Statistics/NHST/Hypothesis/Null hypothesis
exextra[Type]: Interpretating output, Conceptual
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy