```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-237-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-237-en-data.csv", recursive = TRUE)
```

Question
========
A researcher doubts whether he would not be better off becoming an athlete after all, and if he chooses to do so, what sport would be best for him. To determine this for himself, he drew a sample from all professional athletes in the U.S. and determined what their average annual income was (in 10,000 dollars). In addition, he determined what sport [Football = 1, Basketball = 2, Baseball = 3] someone did, and whether it was a male [Gender = 0] or female [Gender = 1] athlete.

Perform an appropriate test where you include sports and gender as independent variables and income as the dependent variable. What is the Sum of Squares for the factor with the least significant main effect (3 decimal places)?

* Download**: [SPSS file](eur-inferential_statistics-237-en-data.sav), [CSV file](eur-inferential_statistics-237-en-data.csv)


Solution
========
The answer is 33,849.

Meta-information
================
exname: eur-inferential_statistics-237-en
extype: num
exsolution: 33.849
extol: 0
exsection: Inferential Statistics/Parametric Techniques/ANOVA/Twoway ANOVA
exextra[ID]: 23f5d
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
