```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-206-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-206-nl-data.csv", recursive = TRUE)
```

Question
========
Sorteer de antwoorden op stelling 2 (variabele: stelling2) in aflopende volgorde (van hoog naar laag) en de cijfers op het tentamen inleiding in de sociologie (variabele: inleiding_sociologie) in oplopende volgorde (van laag naar hoog). Schrijf het cijfer voor het tentamen van wiskunde (variabele: wiskunde) van de 50ste persoon in het antwoordvakje (met 3 cijfers achter de komma).

n.b. Als in jouw bestand de variabelenamen op de eerste rij zitten, dan heb je de 51ste rij nodig.

**Download**: [SPSS file](eur-descriptive-206-nl-data.sav), [CSV file](eur-descriptive-206-nl-data.csv)


Solution
========
Het correcte antwoord is 5.537.


Meta-information
================
exname: eur-descriptive-206-nl
extype: num
exsolution: 5.537
extol: 0
exsection: Variable type/Discrete variable
exextra[Type]: Case
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy