```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
A test that measures assertiveness is administered both before and after an assertiveness training. The variance in the pre‐test is 8 and the reliability is .75. The post‐test has a variance of 7 and the reliability is .80. The correlation between the pre‐ and post‐test scores is .65.
Calculate the reliability of the differences scores.

$R_d = \frac{S^2_{Xo} \times R_{XX} + S^2_{Yo} \times R_{YY}-2\times r_{XoYo}\times\ S_{Xo} \times S_{Yo}}{S^2_{XO} + S^2_{YO} - 2\times r_{XoYo}\times\ S_{Xo} \times S_{Yo}}$


Solution
========
To calculate the reliability of the differences scores, one has to use the beforementioned formula, giving us the following outcome: 
$R_d = \frac{8 \times .75+7\times.80-2\times.65\times\sqrt{8\times7}}{8+7-2\times.65\times \sqrt{8\times7}} = \frac{1.87}{5.27} = .355$


Meta-information
================
exname: eur-reliability-115-en
extype: num
exsolution: .355
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[Type]: Calculation
exextra[Program]: Calculator
exextra[Language]: English
exextra[Level]: Statistical Literacy
