```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-234-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-234-en-data.csv", recursive = TRUE)
```

Question
========
A researcher doubts whether he would not be better off becoming an athlete after all, and if he chooses to do so, what sport would be best for him. To determine this for himself, he drew a sample from all professional athletes in the U.S. and determined what their average annual income was (in 10,000 dollars). In addition, he determined what sport [Football = 1, Basketball = 2, Baseball = 3] someone did, and whether it was a male [Gender = 0] or female [Gender = 1] athlete.

Test whether there is a difference between the three different sports [Sports] in average income [Income]. Give the F value. (3 decimal places)

* Download**: [SPSS file](eur-inferential_statistics-234-en-data.sav), [CSV file](eur-inferential_statistics-234-en-data.csv)


Solution
========
The correct answer is 0.707.

Meta-information
================
exname: eur-inferential_statistics-234-en
extype: num
exsolution: 0.707
extol: 0
exsection: Inferential Statistics/Parametric Techniques/ANOVA/Oneway ANOVA, Inferential Statistics/NHST/Test statistic/F-statistic
exextra[ID]: 59d19
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
