```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-267-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-267-en-data.csv", recursive = TRUE)
```

Question
========
Test whether the mean grade on course exam 1.6 (variable course1_6) for students living with their parents [livingparent = 1] deviates significantly from the mean grade of students who live away from their parents [livingparent = 0]. Write the observed p-value in the answer box (with 3 decimal places). Caution: Report the p-value SPSS gives. You do not have to divide by 2.

**Download**: [SPSS file](eur-inferential_statistics-267-en-data.sav), [CSV file](eur-inferential_statistics-267-en-data.csv)


Solution
========
The correct solution is 0.462.


Meta-information
================
exname: eur-inferential_statistics-267-en
extype: num
exsolution: 0.462
extol: 0
exsection: Inferential Statistics/NHST/p-value, Inferential Statistics/Parametric Techniques/t-test/Independent samples means
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
