```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-415-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-415-en-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker van het instituut voor psychologie doet onderzoek naar alcoholmisbruik onder adolescenten. De onderzoeker ontwierp 34 stellingen waar de adolescenten het mee eens of oneens kunnen zijn op een vierpuntsschaal (1. helemaal mee eens; 2. enigszins mee eens; 3. enigszins mee oneens; 4. helemaal mee oneens). Een voorbeeld van een stelling is: Als ik me eenzaam voel, drink ik graag een alcoholische drank. De antwoorden van 312 meisjes (gender = 0) en jongens (gender = 1) op de 34 stellingen zitten in de dataset. Ook IQ-scores (IQ), schaalscores (scale) en de hoeveelheid alcoholgebruik (alcohol_use; 1 = heel vaak; 2 = vaak; 3 = soms; 4 = nooit) zijn in de dataset opgenomen.

Converteer de schaalscore van elke adolescent naar een genormaliseerde score met een gemiddelde van 10 en een standaardafwijking van 5. Rond de genormaliseerde score af. Wat is de genormaliseerde schaalscore van de adolescent met id=31? (geen decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-descriptive-415-en-data.sav), [CSV file](eur-descriptive-415-en-data.csv)


Solution
========
De genormaliseerde schaalscore van de adolescent met id=31 is 13 (normaliseer de scores met behulp van ranggevallen en transformeer de scores vervolgens zodat de nieuwe variabele een gemiddelde van 10 en een standaardafwijking van 5 heeft).

Meta-information
================
exname: eur-descriptive-415-nl
extype: num
exsolution: 13
extol: 0
exsection: Descriptive statistics
exextra[Type]: Data manipulation, Interpreting output, Calculation, Case
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
