```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-406-en-data.sav", recursive = TRUE)
include_supplement("eur-reliability-406-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. 

Which item has the lowest correlation with the total score excluding the item itself? (no decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-reliability-406-en-data.sav), [CSV file](eur-reliability-406-en-data.csv)


Solution
========
The item that has the lowest correlation with the total score (excluding the item itself) is item 29. Ask for scale if item deleted descriptives when conducting the reliability analysis and look for the item with the lowest item-corrected total correlation.


Meta-information
================
exname: eur-reliability-406-en
extype: num
exsolution: 29
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha, Reliability/Descriptives
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy