```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-123-nl-data.sav", recursive = TRUE)
include_supplement("eur-reliability-123-nl-data.csv", recursive = TRUE)
```

Question
========
*Werk voor psychologen en pedagogen.*

Een wetenschapper heeft de opdracht gekregen om te onderzoeken of het afgestudeerde psychologen en pedagogen lukt om een baan op niveau te vinden. De onderzoeker heeft hiertoe zelf een vragenlijst ontworpen bestaande uit 12 Likert items met 5 antwoordmogelijkheden die variëren van helemaal mee oneens (1) tot helemaal mee eens (5). Een voorbeeld van een item is: Ik heb veel moeite moeten doen om een vacature voor een baan op niveau te vinden. De antwoorden van 608 pedagogen en psychologen op de twaalf items staan weergegeven in het databestand, waarbij de variabele [psy_ped] pedagogen (1) en psychologen (2) onderscheidt. NB. De totaalscore over de 12 items geeft aan hoe moeilijk iemand het vindt om een baan op niveau te vinden. Hoe hoger de totaalscore des te moeilijker hij/zij het vindt om een baan op niveau te vinden.

Open het databestand.

Uit eerder onderzoek is gebleken dat psychologen meer problemen ondervinden om een baan te vinden dan pedagogen. Een onderzoeker wil om deze reden de betrouwbaarheid van de vragenlijst voor psychologen en pedagogen apart berekenen (variabele [psy_ped] ). Wat is de betrouwbaarheid (Cronbach's Alpha) van de vragenlijst voor de pedagogen? (3 decimalen)


**Download**: [SPSS file](eur-reliability-123-nl-data.sav), [CSV file](eur-reliability-123-nl-data.csv)

Solution
========
De betrouwbaarheid (Cronbach's Alpha) van de schaal voor de pedagogen is 0.780.


Meta-information
================
exname: eur-reliability-123-nl
extype: num
exsolution: 53.189
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha, Descriptive statistics/Summary Statistics/Measures of Spread/Standard Deviation
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy