```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-404-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-404-en-data.csv", recursive = TRUE)
```

Question
========
Een kennistest over alcohol bevat 20 items en wordt afgenomen bij 202 middelbare scholieren. De variabele [totaalscore] geeft de totale juiste scores. Geslacht (0 = vrouw; 1 = man) en alcoholgebruik (0 = heel vaak; 1 = vaak; 2 = soms; 3 = nooit) zijn ook opgenomen in de dataset.

Hoeveel studenten hebben een totaalscore die meer dan 2 standaarddeviaties boven het groepsgemiddelde ligt? (geen decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-descriptive-404-en-data.sav), [CSV file](eur-descriptive-404-en-data.csv)


Solution
========
Het aantal studenten met een totaalscore die meer dan 2 standaarddeviaties boven het gemiddelde ligt is drie (bereken z-scores en zoek naar z-scores groter dan 2).

Meta-information
================
exname: eur-descriptive-404-nl
extype: num
exsolution: 3
extol: 0
exsection: Descriptive statistics/Score interpretation/z-score
exextra[Type]: Data manipulation, Interpreting output
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Thinking
