```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
Stel je de volgende twee scenario's voor:

- Je hebt twee verschillende, maar parallelle tests die hetzelfde construct meten, waarbij elke test uit 8 items bestaat. Je berekent een schatting van de betrouwbaarheid van de test in alternatieve vormen (correlatie tussen alternatieve vormen van een test).
- Je hebt één test die uit 16 items bestaat. Je berekent de split-half schatting van de betrouwbaarheid van de test.

Leg uit waarom de (split-half) schatting van de betrouwbaarheid van de 16-item schaal hoger is dan de (alternatieve vormen) schatting van de betrouwbaarheid van de 8-item schaal.


Solution
========
De (split-half) schatting van de betrouwbaarheid van de 16-item schaal is hoger dan de (alternatieve vormen) schatting van de betrouwbaarheid van de 8-item schaal vanwege de langere testlengte. In het algemeen geldt: hoe meer metingen men doet van één construct, hoe hoger de betrouwbaarheid van de (gemiddelde) meting zal zijn. S - ceteris paribus - een schaalscore gebaseerd op 16 items is betrouwbaarder dan een schaalscore gebaseerd op 8 items.

Meta-information
================
exname: eur-reliability-103-nl
extype: string
exsolution: ""
extol: 
exsection: Reliability/Analysis/Parallel forms, Reliability/Analysis/Test-retest
exextra[ID]: c1dbf
exextra[Type]: Conceptual
exextra[Program]: 
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
