```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-408-nl-data.sav", recursive = TRUE)
include_supplement("eur-reliability-408-nl-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker aan het psychologie-instituut onderzoekt alcoholmisbruik onder adolescenten. De onderzoeker heeft 34 uitspraken ontworpen waarmee adolescenten het eens of oneens kunnen zijn op een vierpuntsschaal (1 = helemaal mee eens; 2 = enigszins mee eens; 3 = enigszins mee oneens; 4 = helemaal mee oneens). Een voorbeeld van een uitspraak is: Wanneer ik me eenzaam voel, geniet ik van het drinken van een alcoholisch drankje. De antwoorden van 312 meisjes (0) en jongens (1) op de 34 uitspraken staan in de dataset.

Eerder onderzoek heeft aangetoond dat jongens meer alcohol misbruiken dan meisjes. Vanwege deze bevinding wil een onderzoeker de betrouwbaarheid van de vragenlijst apart berekenen voor jongens en meisjes (variabele [geslacht]). Wat is de betrouwbaarheid (Cronbach’s alpha) van de schaal voor de meisjes? (3 decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

**Download** [SPSS file](eur-reliability-408-nl-data.sav), [CSV file](eur-reliability-408-nl-data.csv)


Solution
========
De betrouwbaarheid (Cronbach's alpha) van de schaal voor de meisjes is 0.493 (zet de split file-optie aan om subgroepen op basis van geslacht te maken voordat je de analyse uitvoert).

Meta-information
================
exname: eur-reliability-408-nl
extype: num
exsolution: 0.493
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
