```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-415-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-415-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1. completely agree; 2. somewhat agree; 3. somewhat disagree; 4. completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. Also included in the dataset are IQ scores, scale scores and the amount of alcohol use (1 = very often; 2 = often; 3 = sometimes; 4 = never).

Convert the scale score of each adolescent to a normalized score with a mean of 10 and a standard deviation of 5. Round the normalized score. What is the normalized scale score of the adolescent with id=31? (no decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-415-en-data.sav), [CSV file](eur-descriptive-415-en-data.csv)


Solution
========
The normalized scale score of the adolescent with id=31 is 13 (normalize the scores using rank cases and then transform the scores so the new variable has a mean of 10 and a standard deviation of 5).


Meta-information
================
exname: eur-descriptive-415-en
extype: num
exsolution: 13
extol: 0
exsection: Descriptive statistics
exextra[Type]: Data manipulation, Interpreting output, Calculation, Case
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy