```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-209-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-209-nl-data.csv", recursive = TRUE)
```

Question
========
The researcher wants to reduce the 7-point scale for proposition 2 (variable: proposition2) to a 5-point scale: answer options 1 and 2 are merged into option 2 and answer options 6 and 7 are merged into option 6. The remaining options, namely 3, 4 and 5, remain the same. Calculate the average examination grade for methods theory (variable: methods theory) for the students in the new option 2 of Theorem 2. Write your answer in the answer box with 5 decimal places.

* Download**: [SPSS file](eur-descriptive-209-nl-data.sav), [CSV file](eur-descriptive-209-nl-data.csv)


Solution
========
The correct answer is 4.62320.

Meta-information
================
exname: eur-descriptive-209-en
extype: num
exsolution: 4.62320
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[Type]: Data manipulation, Calculation
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
