```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-219-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-219-nl-data.csv", recursive = TRUE)
```

Question
========
Onder economiestudenten aan de EUR is een onderzoek gedaan naar de houding van studenten ten opzichte van macro-economie (variabele: macro_economie). Stelling 1 was "macro-economie is nuttig in het kader van deze studie". Deze stelling moest op een 7-punts Likert schaal worden beantwoord, waarbij 1 = helemaal mee oneens en 7 = helemaal mee eens. Hoeveel procent van de studenten heeft een score 7 (helemaal mee eens) gegeven? Schrijf het percentage (met 1 cijfer achter de komma) in het antwoordvakje.

**Download**: [SPSS file](eur-descriptive-219-nl-data.sav), [CSV file](eur-descriptive-219-nl-data.csv)


Solution
========
Het correcte antwoord is 13.6.


Meta-information
================
exname: eur-descriptive-219-nl
extype: num
exsolution: 13.6
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile, Descriptive statistics/Summary Statistics/Proportion
exextra[Type]: Calculation
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
