```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-403-en-data.sav", recursive = TRUE)
include_supplement("eur-reliability-403-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed a questionnaire with 12 items using Likert scales ranging from 1 (completely disagree) to 5 (completely agree). An example of an item is: When I go out, I often consume more than 5 alcoholic beverages. The answers of 608 adolescent girls (1) and boys (2) to the 12 items are in the dataset. Note: higher scores on the questionnaire reflect more alcohol abuse.

Previous research has shown that boys engage in more alcohol abuse than girls. Because of this finding, a researcher wants to calculate the reliability of the questionnaire for boys and girls separately (variable [gender]). What is the reliability (Cronbach’s alpha) of the scale for the girls? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-reliability-403-en-data.sav), [CSV file](eur-reliability-403-en-data.csv)


Solution
========
The reliability (Cronbach's alpha) of the scale for the girls is 0.780 (turn on split file to create subgroups for gender before conducting the analysis).


Meta-information
================
exname: eur-reliability-403-en
extype: num
exsolution: 0.780
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[ID]: 9bc7d
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
