```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-402-en-data.sav", recursive = TRUE)
include_supplement("eur-factor-402-en-data.csv", recursive = TRUE)
```

Question
========
A researcher investigates the factors that may explain alcohol abuse among the elderly. Based on the theory, the researcher suspects that different dimensions can be distinguished concerning alcohol abuse. She designed 34 statements the elderly can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The questionnaire was administered to 312 elderly (>70 years). The responses of the participants to the 34 statements are given in the dataset.

When 3 factors are extracted, what is the percentage of the variance of the extracted sums of squared loadings that is explained by the 3 factors combined? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-factor-402-en-data.sav), [CSV file](eur-factor-402-en-data.csv)


Solution
========
The percentage of variance explained by the three factors combined is 16.441% (look for the extraction sums of squared loadings and then the cumulative %).


Meta-information
================
exname: eur-factor-402-en
extype: num
exsolution: 16.441
extol: 0
exsection: Factor analysis/Explained variance, Factor analysis/Exploratory factor analysis
exextra[Type]: Performing analysis, Interpreting output
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy