```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-403-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-403-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. Also included in the dataset are IQ scores, scale scores and the amount of alcohol use (1 = very often; 2 = often; 3 = sometimes; 4 = never).

The researcher wants to investigate whether he can predict the scale score with IQ (variable [IQ])and wonders whether this relation is different for boys and girls. Conduct a regression analysis to investigate this question. What is the standard error of the regression coefficient of the interaction effect gender x IQ? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-inferential_statistics-403-en-data.sav), [CSV file](eur-inferential_statistics-403-en-data.csv)


Solution
========
The standard error of the regression coefficient for the interaction effect (gender x IQ) is 0.014. First compute an interaction variable (gender*IQ). Then use regression to predict the scale score with gender, IQ and the interaction as the predictors. Finally find the standard error for the interaction effect.


Meta-information
================
exname: eur-inferential_statistics-403-en
extype: num
exsolution: 0.014
extol: 0
exsection: Inferential Statistics/Regression/Slope, Inferential Statistics/Regression/Simple linear regression
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
