```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-417-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-417-en-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker van het psychologisch instituut doet onderzoek naar alcoholmisbruik onder adolescenten. De onderzoeker ontwierp 34 stellingen waar de adolescenten het mee eens of oneens kunnen zijn op een vierpuntsschaal (1. helemaal mee eens; 2. enigszins mee eens; 3. enigszins mee oneens; 4. helemaal mee oneens). Een voorbeeld van een stelling is: Als ik me eenzaam voel, drink ik graag een alcoholische drank. De antwoorden van 312 meisjes (gender = 0) en jongens (gender = 1) op de 34 stellingen zitten in de dataset. Ook IQ-scores (IQ), schaalscores (scale) en de hoeveelheid alcoholgebruik (alcohol_use; 1 = heel vaak; 2 = vaak; 3 = soms; 4 = nooit) zijn in de dataset opgenomen.

Maak een groep met daarin de 33,333% hoogst scorende adolescenten op de schaalscore (variabele [scale]). Wat is het gemiddelde van deze groep op de variabele [IQ]? (2 decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-descriptive-417-en-data.sav), [CSV file](eur-descriptive-417-en-data.csv)


Solution
========
Het gemiddelde IQ van deze groep is 109,17. Eerst moet een nieuwe variabele worden berekend met behulp van de percentielscores en de hercodering naar verschillende variabele functies. Vind daarna het gemiddelde IQ van deze hoogst scorende groep.

Meta-information
================
exname: eur-descriptive-417-nl
extype: num
exsolution: 109.17
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[ID]: 9d634
exextra[Type]: Data manipulation, Interpreting output, Calculation
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
