```{r, echo = FALSE, results = "hide"}
include_supplement("eur-reliability-408-en-data.sav", recursive = TRUE)
include_supplement("eur-reliability-408-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1 = completely agree; 2 = somewhat agree; 3 = somewhat disagree; 4 = completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset.

Previous research has shown that boys engage in more alcohol abuse than girls. Because of this finding, a researcher wants to calculate the reliability of the questionnaire for boys and girls separately (variable [gender]). What is the reliability (Cronbach’s alpha) of the scale for the girls? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-reliability-408-en-data.sav), [CSV file](eur-reliability-408-en-data.csv)


Solution
========
The reliability (Cronbach's alpha) of the scale for the girls is 0.493 (turn on split file to create subgroups for gender before conducting the analysis).


Meta-information
================
exname: eur-reliability-408-en
extype: num
exsolution: 0.493
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[Type]: Interpretating output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy