```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-402-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-402-en-data.csv", recursive = TRUE)
```

Question
========
A knowledge test on alcohol contains 20 items and is administered to 202 high school students. The variable [total score] gives the total correct scores. Gender (0 = woman; 1 = man) and alcohol use (0 = very often; 1 = often; 2 = sometimes; 3 = never) are also included in the dataset. 

A researcher thinks that there is a difference in total score between students who drink a) very often, b) often,  c) sometimes, and d) never (variable [alcohol_use]). Conduct an Anova to investigate the difference in alcohol use among these groups of students. What is the effect size (partial eta squared) of this effect? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-inferential_statistics-402-en-data.sav), [CSV file](eur-inferential_statistics-402-en-data.csv)


Solution
========
The effect size (partial eta squared) of the effect of alcohol use on the total score is 0.007 (conduct an ANOVA using General Linear Model: Univariate and ask for estimates of effect size).


Meta-information
================
exname: eur-inferential_statistics-402-en
extype: num
exsolution: 0.007
extol: 0
exsection: Inferential Statistics/Effect size/Eta squared, Inferential Statistics/Parametric Techniques/ANOVA/Oneway ANOVA
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
