```{r, echo = FALSE, results = "hide"}
#Load package
library(knitr)
```

Question
========
Calculate the 95% Confidence Interval of a student who has a grade of 5.2 given a reliability of .31 for the exam. The variance of the grades is 4
Formula for the 95% confidence interval: $95\% CI = X_o ± Z_{p=95} \times se_m$
Formula for standard error of measurement is: $se_m = s_o \times \sqrt{1 - R_{xx}}$


Solution
========
You will need the formula for the 95% confidence interval: $95\% CI = X_o ± Z_{p=95} \times se_m$

$95\% CI = 5.2 ± 1.96 \times se_m$

$se_m = 2 \times \sqrt {1-.31} = 1.662$

$95\% CI = 5.2 ± 1.96 \times 1.662 = 5.2 ± 3.26$

The 95% CI of grade 5.2 is $[1.94-8.46]$


Meta-information
================
exname: eur-inferential_statistics-204-en
extype: string
exsolution: ""
extol: 
exsection: Inferential Statistics/Confidence Intervals/Margin of error, Inferential Statistics/Confidence Intervals/Width
exextra[Type]: Calculate
exextra[Program]: Calculator
exextra[Language]: English
exextra[Level]: Statistical Literacy
