```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-239-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-239-en-data.csv", recursive = TRUE)
```

Question
========
A researcher doubts whether he would not be better off becoming an athlete after all, and if he chooses to do so, what sport would be best for him. To determine this for himself, he drew a sample from all professional athletes in the U.S. and determined what their average annual income was (in 10,000 dollars). In addition, he determined what sport [Football = 1, Basketball = 2, Baseball = 3] someone did, and whether it was a male [Gender = 0] or female [Gender = 1] athlete.

What is the effect size [partial eta squared] of the interaction effect of type of sport [Sport] and gender [Gender]? (3 decimal places)

* Download**: [SPSS file](eur-inferential_statistics-239-en-data.sav), [CSV file](eur-inferential_statistics-239-en-data.csv)


Solution
========
The answer is 0.028.

Meta-information
================
exname: eur-inferential_statistics-239-en
extype: num
exsolution: 0.028
extol: 0
exsection: Inferential Statistics/Parametric Techniques/ANOVA/Twoway ANOVA, Inferential Statistics/Effect size/Eta squared
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
