```{r, echo = FALSE, results = "hide"}
#Load package
library(knitr)
```

Question
========
Suppose that you calculate the 95% interval around a participant's observed score in order to estimate their true score, how would you interpret it? Give the theoretical and practical interpretation of the confidence interval of the true score.


Solution
========
Theoretical interpretation: the probability that this (particular) confidence interval contains the true score is .95. If we test an individual 100 times (e.g., with parallel tests) and we obtain 100 different intervals, 95% of these should contain participants' true score, with our confidence interval likely being one of the 95 that do contain the true score.

Practical interpretation: We are 95% confident that the individuals true score lies between [lower limit, upper limit]. When the interval is large because of a large amount of error (low reliability), it indicates that we can not accurately interpret the observed score.


Meta-information
================
exname: eur-inferential_statistics-205-en
extype: string
exsolution: ""
extol: 
exsection: Inferential Statistics/Confidence Intervals/Confidence level, Inferential Statistics/Confidence Intervals/Testing, Inferential Statistics/Confidence Intervals/Width, Inferential Statistics/Confidence Intervals/Margin of error
exextra[Type]: Conceptual
exextra[Program]: Calculator
exextra[Language]: English
exextra[Level]: Statistical Literacy
