```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
The “Three Minutes Test” (TMT) is a test to assess technical reading level. Children have to accurately read as many words as possible during three minutes. A teacher from grade 5 wants to use the test, which was constructed for children in grade 2, to assess the reading skills of her grade 5 children.
Cronbach’s alpha based on the grade 2 population is .88 and the standard deviation of the test scores in grade 2 is 3.

The standard deviation of the observed scores in grade 5 turned out to be 2.5. Calculate the reliability of the TMT in grade 5 and assume that the error variance is equal for the grade 2 and grade 5 populations. Use the following formula, but note that you might have to alter the formula in some way:

$r_{xx} = \frac{S^2_{X_t}}{S^2_{X_o}}$

And

$S^2_{X_o}= S^2_{X_t} + S^2_{X_e}$


Solution
========
We can calculate the error variance by using: $r_{xx} = \frac{S^2_{X_t}}{S^2_{X_o}} = \frac{S^2_{X_0}-S^2_{X_t}}{S^2_{X_o}}$.We can fill in the reliability (.88) and the variance (3^2) of the scores of grade 2: $.88 = \frac{9-S^2_{X_t}}{9}$. Then, the variance of the error is: $.88 \times 9 - 9 = - s^2_{x_e}$, thus $s^2_{x_e} = 1.08$ and $s_{x_e} = 1.04$. We can use this error variance to calculate the reliability in grade 5:$r_{xx} = \frac{S^2_{X_t}}{S^2_{X_o}} = \frac{2.5^2-1.08}{2.5^2} = \frac{5.17}{6.25}$ = .827.


Meta-information
================
exname: eur-reliability-114-en
extype: num
exsolution: .827
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[Type]: Calculate
exextra[Program]: Calculator
exextra[Language]: English
exextra[Level]: Statistical Literacy
