```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-123-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-123-nl-data.csv", recursive = TRUE)
```

Question
========
*Kennis over het beroepsveld.*

Een kennistoets over het beroepsveld van psychologen en pedagogen bestaat uit 20 items en is afgenomen bij 202 studenten uit de master psychologie en pedagogiek. Het totale aantal correct beantwoorde vragen is weergegeven in de variabele [totaalscore]. Daarnaast zijn de scores (0 = niet correct, 1 = correct) op item 8 uit bovengenoemde kennistoets weergegeven in de variabele [item8]. 

Open het databestand.

Identificeer op basis van de scores een groep die bestaat uit de personen met een score van 12 of lager op de variabele [totaalscore]. Wat is de proportie correct van deze groep op item 8? (3 decimalen)

**Download**: [SPSS file](eur-descriptive-123-nl-data.sav), [CSV file](eur-descriptive-123-nl-data.csv)


Solution
========
De proportie correct van deze groep op item 8 is .62. Dit betekent dat 62% van de studenten in deze groep item 8 correct beantwoord heeft.


Meta-information
================
exname: eur-descriptive-123-nl
extype: num
exsolution: .62
extol: 0
exsection: Descriptive statistics/Summary Statistics/Proportion
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
