```{r, echo = FALSE, results = "hide"}
include_supplement("eur-assumptions-103-en-data.sav", recursive = TRUE)
include_supplement("eur-assumptions-103-en-data.csv", recursive = TRUE)
```

Question
========
*Long-term detention*

Currently, in the Netherlands, there is debate about the usefulness of long-term detention with psychiatric treatment. A psychiatrist of a Dutch long-term detention centre collected data about aggression of detainees. The detainees were observed during group treatment sessions and the level of aggressive behavior was rated at four points in time: (1) 2 days after their admission to the centre [T1_aggression] ; (2) half a year after admission [T2_aggression]; (3) a year after admission [T3_aggression]; and (4) a year and a half after admission [T4_aggression]. The level of aggressive behavior was rated by means of a semi-structured interview, resulting in scores ranging from 0 (not aggressive) to 40 (extremely aggressive). Furthermore, the psychiatrist registered whether detainees suffered from psychosis or not [psychosis].

Open the data file.

Perform the relevant ANOVA to test for differences on the four aggression measurements and make sure to test the sphericity assumption. What is the value of Greenhouse-Geisser Epsilon for this model? (3 decimals)

**Download**: [SPSS file](eur-assumptions-103-en-data.sav), [CSV file](eur-assumptions-103-en-data.csv)


Solution
========
The Greenhouse-Geisser Epsilon is 0.935.


Meta-information
================
exname: eur-assumptions-103-en
extype: num
exsolution: 0.935
extol: 0
exsection: Assumptions/Sphericity/Epsilon, Inferential Statistics/Parametric Techniques/ANOVA/Oneway repeated measures ANOVA
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy