```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-409-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-409-en-data.csv", recursive = TRUE)
```

Question
========
A knowledge test on alcohol contains 20 items and is administered to 202 high school students. The variable [total score] gives the total correct scores. Gender (0 = woman; 1 = man) and alcohol use (0 = very often; 1 = often; 2 = sometimes; 3 = never) are also included in the dataset. 

Create a p_low group containing the 33.333% lowest scoring students on the total score [total score]. What is the proportion correct score of this group on item 8? (3 decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-409-en-data.sav), [CSV file](eur-descriptive-409-en-data.csv)


Solution
========
The proportion correct of the p_low group on item 8 is 0.62. First a new variable has to be computed using the percentile scores and the recode into different variable function. After, find the mean of the p_low group on item8. This mean represents the proportion correct on this item.


Meta-information
================
exname: eur-descriptive-409-en
extype: num
exsolution: 0.62
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[Type]: Data manipulation, Interpreting output, Calculation
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
