```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-204-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-204-en-data.csv", recursive = TRUE)
```

Question
========
Feyenoord- en Ajax-fans hebben vaak kritiek op elkaars team. We kijken naar van welk team iemand fan is [Fan, waarbij Feyenoord = 0 en Ajax = 1], in welke stad iemand woont [Stad, waarbij Rotterdam = 1, Amsterdam = 2, Dordrecht = 3 en Haarlem = 4], het aantal wedstrijden gespeeld door het favoriete team dat iemand in de loop der jaren heeft bekeken (dus het aantal wedstrijden gespeeld door Feyenoord bekeken door een Feyenoord-fan) [played_favourite], en het aantal wedstrijden gespeeld door het andere team dat iemand in de loop der jaren heeft bekeken [played_other]. We hebben ook geregistreerd wiens team de afgelopen 4 jaar kampioen van de divisie is geworden [Kampioen, waarbij Geen kampioenschap = 0 en Kampioenschap = 1].

Wat is het gemiddelde aantal wedstrijden dat iemand keek toen het favoriete team van Ajax-fans speelde [Fan=1]? Rapporteer de verkregen waarde (met 3 decimalen).

* Download**: [SPSS file](eur-descriptive-204-en-data.sav), [CSV file](eur-descriptive-204-en-data.csv)


Solution
========
Het juiste antwoord is 96,686

Meta-information
================
exname: eur-descriptive-204-nl
extype: num
exsolution: 96.686
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[ID]: 55a4b
exextra[Type]: Calculation
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
