```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-401-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-401-en-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker van het instituut voor psychologie doet onderzoek naar alcoholmisbruik onder adolescenten. De onderzoeker ontwierp een vragenlijst met 12 items op Likert-schalen van 1 (helemaal mee oneens) tot 5 (helemaal mee eens). Een voorbeeld van een item is: Als ik uitga, drink ik vaak meer dan 5 alcoholische dranken. De antwoorden van 608 adolescente meisjes (gender = 1) en jongens (gender = 2) op de 12 items zitten in de dataset. Let op: hogere scores op de vragenlijst duiden op meer alcoholmisbruik.

Op welke van de 12 items geven de adolescenten de minst gevarieerde antwoorden? (geen decimalen)

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-descriptive-401-en-data.sav), [CSV file](eur-descriptive-401-en-data.csv)


Solution
========
Het item met de minst gevarieerde antwoorden is item 2 (vraag om beschrijvende statistieken en kijk naar de varianties van alle items).

Meta-information
================
exname: eur-descriptive-401-nl
extype: num
exsolution: 2
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Spread/Standard Deviation
exextra[ID]: 2330d
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
