
```{r, echo = FALSE, results = "hide"}
include_supplement("eur-assumptions-105-nl-data.sav", recursive = TRUE)
include_supplement("eur-assumptions-105-nl-data.csv", recursive = TRUE)
```

Question
========
*Testing effect* 

Uit onderzoek is gebleken dat wanneer mensen gezichten van vreemden moeten leren zij deze op de lange termijn beter kunnen onthouden wanneer zij de gezichten eerst bestuderen en daarna zichzelf testen met het koppelen van de gezichten aan de bijbehorende naam, dan wanneer zij de gezichten twee keer bestuderen. Een onderzoeker aan het instituut voor psychologie wil weten of dit zogenaamde testing effect zich ook in het klaslokaal openbaart. Ze deelt een groep van 60 4VWO leerlingen in in drie groepen [condition]. De leerlingen in groep 1 bestuderen 2 keer achter elkaar een lijst met 30 gezichten en de bijbehorende namen (1 = restudy), de leerlingen in groep 2 bestuderen dezelfde gezichten en bijbehorende namen 1 keer en testen zichzelf daarna (2 = testing). Hierbij moeten ze hun hand op de lijst met namen van mensen leggen en zelf bedenken hoe de persoon op de foto heet. Leerlingen in groep 3 bestuderen de gezichten en namen slechts 1 keer (3 = study_once). Een week na het bestuderen krijgen alle leerlingen een test waarbij zij de 30 gezichten te zien krijgen en de bijbehorende naam moeten geven. Het totaal aantal correct geïdentificeerde mensen staat weergegeven in de variabele score [score]. De onderzoeker heeft verder nog voor iedere leerling een sociale vaardigheids-score [sociaal] verzameld.

Open het databestand.

Voer een analyse uit om te bepalen of de regressielijnen die de relatie tussen sociale vaardigheids-score [sociaal] en prestatie op de test [score] weergeven verschillen voor de drie condities [condition]. Wat is de p-waarde behorend bij de F-toets die de homogeniteit van regressie assumptie toetst? (3 decimalen)

**Download**: [SPSS file](eur-assumptions-105-nl-data.sav), [CSV file](eur-assumptions-105-nl-data.csv)

Solution
========
De p-waarde is .872. De juiste analyse is ANCOVA waarbij je de twee hoofdeffecten van conditie en Frans + hun interactie (conditie*Frans) toetst. De F-waarde voor het interactie-effect is 0.138, de p-waarde is .872.

Meta-information
================
exname: eur-assumptions-105-nl
extype: num
exsolution: .872
extol: 0
exsection: Assumptions/Homogeneity of variance/Levene's test, Inferential Statistics/NHST/p-value
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
