```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-401-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-401-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed a questionnaire with 12 items using Likert scales ranging from 1 (completely disagree) to 5 (completely agree). An example of an item is: When I go out, I often consume more than 5 alcoholic beverages. The answers of 608 adolescent girls (1) and boys (2) to the 12 items are in the dataset. Note: higher scores on the questionnaire reflect more alcohol abuse.

To which of the 12 items do the adolescents give the least varied responses? (no decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-401-en-data.sav), [CSV file](eur-descriptive-401-en-data.csv)


Solution
========
The item with the least varied responses is item 2 (ask for descriptive statistics and look at the variances of all the items).


Meta-information
================
exname: eur-descriptive-401-en
extype: num
exsolution: 2
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Spread/Standard Deviation
exextra[Type]: Interpretating output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy