```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-109-nl-data.sav", recursive = TRUE)
include_supplement("eur-factor-109-nl-data.csv", recursive = TRUE)
```

Question
========
*Werk voor psychologen en pedagogen.*

Een wetenschapper doet onderzoek naar factoren die kunnen verklaren waarom de carriëremogelijkheden voor psychologen en pedagogen soms gering zijn. Vanuit theoretische inzichten over carriëremogelijkheden heeft de onderzoeker het idee dat er verschillende dimensies onderscheiden kunnen worden die iets te maken hebben met de carriëremogelijkheden. Ze heeft 34 stellingen bedacht waarop respondenten op een 4-puntsschaal (1. helemaal mee eens; 2. een beetje mee eens; 3. niet zo erg mee eens; 4. helemaal niet mee eens) aan kunnen geven of ze het eens zijn met een stelling. Een voorbeeld van een stelling is: “Ik heb tijdens mijn opleiding een relevante stage gelopen”. De vragenlijst is afgenomen bij 312 afgestudeerden. De responsen van de deelnemers op de 34 stellingen staan weergegeven in het databestand. 

Open het databestand.

Voer een ongeroteerde exploratieve factor analyse uit met principal axis factoring waarbij je alle stellingen uit de vragenlijst opneemt en waarbij 3 factoren worden geëxtraheerd. 
Hoeveel procent van de totale variantie verklaren de eerste drie factoren samen wanneer er 3 factoren worden geëxtraheerd?  (1 decimaal)

**Download**: [SPSS file](eur-factor-109-nl-data.sav), [CSV file](eur-factor-109-nl-data.csv)


Solution
========
16.4% variantie van alle items kun je verklaren wanneer de eerste drie factoren worden geëxtraheerd (zie extraction sums of squared loadings, cumulative %).


Meta-information
================
exname: eur-factor-109-nl
extype: num
exsolution: 16.4
extol: 0
exsection: Factor analysis/Explained variance
exextra[ID]: e44b1
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
