```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
A psychometrician working at CITO wants to evaluate the criterion validity of a dyslexia test. The reliability of the test $R_{xx}$ has already been investigated and turned out to be .70. The criterion measure is the judgement of a school psychologist which is quite, though not perfectly, reliable: $R_{yy} = $ .80. The observed correlation between the test and criterion turned out to be .6. The psychometrician doubts whether she should calculate the adjusted correlation and what variable she has to adjust; the test, the criterion or both.

Calculate the adjusted correlation by adjusting for the test, criterion or both. What would the correlation be if one (or both) of these elements were to be perfectly reliable? Write down the answer (3 decimals).


Solution
========
$r_{xy-adjusted} = \frac{.6}{\sqrt{.8}} = .671$


Meta-information
================
exname: eur-reliability-117-en
extype: num
exsolution: .671
extol: 0
exsection: Reliability/Analysis/Cronbach's alpha
exextra[Type]: Calculate
exextra[Program]: Calculator
exextra[Language]: English
exextra[Level]: Statistical Literacy
