```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-411-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-411-en-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker van het instituut voor psychologie doet onderzoek naar alcoholmisbruik onder adolescenten. De onderzoeker ontwierp 34 stellingen waar de adolescenten het mee eens of oneens kunnen zijn op een vierpuntsschaal (1. helemaal mee eens; 2. enigszins mee eens; 3. enigszins mee oneens; 4. helemaal mee oneens). Een voorbeeld van een stelling is: Als ik me eenzaam voel, drink ik graag een alcoholische drank. De antwoorden van 312 meisjes (gender = 0) en jongens (gender = 1) op de 34 stellingen zitten in de dataset. Ook IQ-scores (IQ), schaalscores (scale) en de hoeveelheid alcoholgebruik (alcohol_use; 1 = heel vaak; 2 = vaak; 3 = soms; 4 = nooit) zijn in de dataset opgenomen.

Bereken de percentielscores van de schaalscore (variabele [scale]). Wat is het percentage adolescenten met een schaalscore van 23 of lager? Geef het afgeronde percentage. (geen decimalen).

Open de dataset hieronder om deze vraag te beantwoorden:

* Download** [SPSS file](eur-descriptive-411-en-data.sav), [CSV file](eur-descriptive-411-en-data.csv)


Solution
========
Het percentage studenten met een schaalscore van 23 of lager is 8% (percentielen kunnen worden berekend met behulp van ranglijsten).

Meta-information
================
exname: eur-descriptive-411-nl
extype: num
exsolution: 8
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[Type]: Data manipulation, Interpreting output, Calculation
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
