```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-209-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-209-nl-data.csv", recursive = TRUE)
```

Question
========
De onderzoeker wil de 7-puntschaal voor stelling 2 (variabele: stelling2) terugbrengen naar een 5-puntschaal: de antwoordopties 1 en 2 worden samengevoegd tot optie 2 en de antwoordopties 6 en 7 worden samengevoegd tot optie 6. De overige opties, namelijk 3, 4 en 5, blijven gelijk. Bereken het gemiddelde tentamencijfer voor methodenleer (variabele: methodenleer) voor de studenten in de nieuwe optie 2 van stelling 2. Schrijf je antwoord in het antwoordvakje met 5 cijfers achter de komma.

**Download**: [SPSS file](eur-descriptive-209-nl-data.sav), [CSV file](eur-descriptive-209-nl-data.csv)


Solution
========
Het correcte antwoord is 4.62320.


Meta-information
================
exname: eur-descriptive-209-nl
extype: num
exsolution: 4.62320
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Location/Mean
exextra[Type]: Data manipulation, Calculation
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy