```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-119-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-119-nl-data.csv", recursive = TRUE)
```


Question
========
*Knowledge about the professional field.*

A knowledge test about the professional field of psychologists and pedagogues consists of 20 items and was administered to 202 students in the master's program in psychology and pedagogy. The total number of correctly answered questions is shown in the variable [total score].

Open the data file.

Calculate the percentile scores. What percent of all students have a total score of 8 or lower (1 decimal place).

* Download**: [SPSS file](eur-descriptive-119-nl-data.sav), [CSV file](eur-descriptive-119-nl-data.csv)

Solution
========
3.5% of students have an overall score of 8 or lower.

Meta-information
================
exname: eur-descriptive-119-en
extype: num
exsolution: 3.5
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[ID]: 9a60c
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
