```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-120-nl-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-120-nl-data.csv", recursive = TRUE)
```

Question
========
*Kennis over het beroepsveld.*

Een kennistoets over het beroepsveld van psychologen en pedagogen bestaat uit 20 items en is afgenomen bij 202 studenten uit de master psychologie en pedagogiek. Het totale aantal correct beantwoorde vragen is weergegeven in de variabele [totaalscore]. 

Open het databestand.

Hoeveel studenten hebben een totaalscore die groter is dan twee standaarddeviaties boven het gemiddelde in de groep? (geen decimalen)

**Download**: [SPSS file](eur-descriptive-120-nl-data.sav), [CSV file](eur-descriptive-120-nl-data.csv)


Solution
========
Drie studenten hebben een totaalscore die groter is dan twee standaarddeviaties boven het gemiddelde in de groep.
Bereken z-scores voor de variabele [totaalscore]; er zijn drie personen met een z-score groter dan 2.


Meta-information
================
exname: eur-descriptive-120-nl
extype: num
exsolution: 3
extol: 0
exsection: Descriptive statistics/Summary Statistics/Measures of Spread/Standard Deviation
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
