```{r, echo = FALSE, results = "hide"}
include_supplement("eur-assumptions-101-en-data.sav", recursive = TRUE)
include_supplement("eur-assumptions-101-en-data.csv", recursive = TRUE)
```

Question
========
*Testing effect* 

Research has shown that when people learn words from a foreign language they better remember those words if they first study the words and then test themselves trying to recollect the words, compared to just studying the words twice. A researcher from the institute of psychology wants to know whether this so-called testing effect can be proven to exist in the classroom. She divides a group of 60 students into three groups [condition]. The students in group 1 study a list of 30 French words and their Dutch translation twice (1 = restudy). The students in group 2 study the list of 30 French words and their Dutch translation once and then test themselves (2 = testing). The students in group 3 just study the list of 30 French words and their Dutch translation once without testing themselves (3 = study_once). A week after the study phase, the students took a test where they had to give the Dutch translation of the 30 French words that they studied earlier. The total number of correct translations is represented by the variable score [score]. Additionally, the researcher included for each student his/her French grade [French].

Open the data file.

Conduct an analysis to determine whether there is a difference between the three conditions [condition] in terms of total number of correct translations [score]. Test whether there is a violation of the homogeneity of variances assumption for this analysis. What is the F-value for this assumption test? (3 decimals)

**Download**: [SPSS file](eur-assumptions-101-en-data.sav), [CSV file](eur-assumptions-101-en-data.csv)

Solution
========
The F-value is .291. The correct analysis is ANOVA with a so-called homogeneity test. In SPSS this is Levene's test.



Meta-information
================
exname: eur-assumptions-101-en
extype: num
exsolution: .291
extol: 0
exsection: Assumptions/Homogeneity of variance/Levene's test
exextra[ID]: 622fe
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
