```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-247-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-247-en-data.csv", recursive = TRUE)
```

Question
========
Among psychology students, a study was conducted into the attitudes of students towards statistics. Statement 1 was "statistics is useful in the context of this study." This claim had to be answered on a 7-point Likert-scale, where 1 = completely disagree and 7 = completely agree. What is the percentage of students with a score of 1 (completely disagree) on statement 1 (with 1 decimal place).

**Download**: [SPSS file](eur-descriptive-247-en-data.sav), [CSV file](eur-descriptive-247-en-data.csv)


Solution
========
The correct answer is 13.5.


Meta-information
================
exname: eur-descriptive-247-en
extype: num
exsolution: 13.5
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[Type]: Calculation
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy