```{r, echo = FALSE, results = "hide"}
#Load package
library(exams)
library(knitr)
```
Question
========
Imagine the following two scenario's:

- You have two different, yet parallel tests that measure the same construct, with each test consisting of 8 items. You calculate an alternate forms estimate of the test's reliability (correlation between alternate forms of a test).
- You have one test consisting of 16 items. You calculate the split-half estimate of the reliability of the test.

Explain why the (split‐half) estimate of the reliability of the 16-item scale is higher than the (alternate forms) estimate of the reliability of the 8 item scale.


Solution
========
The (split‐half) estimate of the reliability of the 16 item scale is higher than the (alternate forms) estimate of the reliability of the 8 item scale because of its longer test length. In general: the more measurements one takes of a single construct, the higher the reliability of the (average) measurement will be. If everything else remains the same a scale score that is based on 16 items is more reliable than a scale score based on 8 items.


Meta-information
================
exname: eur-reliability-103-en
extype: string
exsolution: ""
extol: 
exsection: Reliability/Analysis/Parallel forms, Reliability/Analysis/Test-retest
exextra[ID]: 74708
exextra[Type]: Conceptual
exextra[Program]: 
exextra[Language]: English
exextra[Level]: Statistical Literacy
