```{r, echo = FALSE, results = "hide"}
include_supplement("eur-descriptive-413-en-data.sav", recursive = TRUE)
include_supplement("eur-descriptive-413-en-data.csv", recursive = TRUE)
```

Question
========
A researcher working at the psychology institute investigates alcohol abuse among adolescents. The researcher designed 34 statements the adolescents can agree or disagree with on a four-point scale (1. completely agree; 2. somewhat agree; 3. somewhat disagree; 4. completely disagree). An example of a statement is: When I feel lonely, I enjoy drinking an alcoholic beverage. The answers of 312 girls (0) and boys (1) to the 34 statements are in the dataset. Also included in the dataset are IQ scores, scale scores and the amount of alcohol use (1 = very often; 2 = often; 3 = sometimes; 4 = never).

What is the scale score corresponding to a percentile score of 30%? (no decimals)

Open the dataset below to answer this question:

**Download** [SPSS file](eur-descriptive-413-en-data.sav), [CSV file](eur-descriptive-413-en-data.csv)


Solution
========
The scale score corresponding to a percentile score of 30% is 25.


Meta-information
================
exname: eur-descriptive-413-en
extype: num
exsolution: 25
extol: 0
exsection: Descriptive statistics/Score interpretation/Percentile
exextra[ID]: 37b82
exextra[Type]: Interpreting output, Performing analysis, Calculation
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
