```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-255-en-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-255-en-data.csv", recursive = TRUE)
```
Question
========
A researcher is aware that he is a very narcissistic person, and wants to switch to a job in which this narcissism is not such a big deal. To determine which job he should choose he takes a random sample of the members of the International Club for Quite Narcissistic People (ICQNP) and determined the degree of narcissism using a questionnaire. In addition, he determined the job [Job, where CEO = 1, Manager = 2 and Statistician = 3] of the participants, and whether they are male [Gender = 0] or female [Gender = 1].

Using the LSD-correction, test the pairwise differences in narcism [Narcism] between the three types of job [Job]. What is the p-value for the difference between Managers [Job=2] en Statisticians [Job=3]? (3 decimals)

**Download**: [SPSS file](eur-inferential_statistics-255-en-data.sav), [CSV file](eur-inferential_statistics-255-en-data.csv)


Solution
========
The correct answer is 0.845.


Meta-information
================
exname: eur-inferential_statistics-255-en
extype: num
exsolution: 0.845
extol: 0
exsection: Inferential Statistics/Parametric Techniques/ANOVA/Oneway ANOVA, Inferential Statistics/Parametric Techniques/ANOVA/Post-hoc test
exextra[Type]: Interpreting output
exextra[Program]: SPSS
exextra[Language]: English
exextra[Level]: Statistical Literacy
