```{r, echo = FALSE, results = "hide"}
include_supplement("eur-factor-407-en-data.sav", recursive = TRUE)
include_supplement("eur-factor-407-en-data.csv", recursive = TRUE)
```

Question
========
Een onderzoeker van het instituut voor psychologie doet onderzoek naar alcoholmisbruik onder adolescenten. De onderzoeker ontwierp 34 stellingen waar de adolescenten het mee eens of oneens kunnen zijn op een vierpuntsschaal (1 = helemaal mee eens; 2 = enigszins mee eens; 3 = enigszins mee oneens; 4 = helemaal mee oneens). Een voorbeeld van een stelling is: Als ik me eenzaam voel, drink ik graag een alcoholische drank. De antwoorden van 312 meisjes (0) en jongens (1) op de 34 stellingen staan in de dataset.

Als er 4 factoren worden geëxtraheerd door principal axis factoring, wat is dan het percentage van de variantie (geëxtraheerde sommen van gekwadrateerde ladingen) dat wordt verklaard door de 4 factoren samen? (3 decimalen)

Open de onderstaande dataset om deze vraag te beantwoorden:

* Download** [SPSS file](eur-factor-407-en-data.sav), [CSV file](eur-factor-407-en-data.csv)


Solution
========
Het percentage variantie dat door de vier factoren samen wordt verklaard, is 21,604% (zoek naar de extractiesommen van gekwadrateerde ladingen en vervolgens naar het cumulatieve %).

Meta-information
================
exname: eur-factor-407-nl
extype: num
exsolution: 21.604
extol: 0
exsection: Factor analysis/Explained variance, Factor analysis/Exploratory factor analysis
exextra[Type]: Interpreting output, Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
