
name: packaging-actions
run-name: ${{ github.actor }} is packaging
on:
  push:
    tags: ['*']

env:
  SOURCE_BRANCH: main
  PACKAGES_BRANCH: packages # ensure that the branch and folder exist
  PACKAGES_FOLDER: packages
  HTML_FOLDER: docs

jobs:
  item-folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install software
        run: sudo apt install make tree

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::base64enc
            any::knitr
            any::rmarkdown
            any::RCurl
            any::magick
            any::openxlsx
            any::png
            any::RJSONIO
            any::xml2
            any::dplyr
            any::readr

      - name: Install Exams developer version
        run: Rscript -e 'install.packages("exams", repos = "http://R-Forge.R-project.org", dependencies = TRUE, type = "source")'


      - name: Set up git
        run: |
          git config user.email "lindemann09@users.noreply.github.com'"
          git config user.name "Github Actions"
          git fetch origin $SOURCE_BRANCH
          git checkout $SOURCE_BRANCH

      - name: Checkout packages
        run: |
          git fetch origin $PACKAGES_BRANCH
          git checkout $PACKAGES_BRANCH
          git checkout $SOURCE_BRANCH
          git checkout $PACKAGES_BRANCH -- $HTML_FOLDER
          git checkout $PACKAGES_BRANCH -- $PACKAGES_FOLDER

      - run: make tarballs_zipped
      - run: make compile
      - run: make fingerprint_file
      - run: make checksums
      - run: make website
      - run: make sharestats_website_csv

      - name: commit results
        run: |
          git checkout $PACKAGES_BRANCH
          ls $PACKAGES_FOLDER -l
          git add $PACKAGES_FOLDER/. --force
          git add $HTML_FOLDER/. --force
          git commit -am "CI packaging"
          git push --set-upstream origin $PACKAGES_BRANCH --force

