```{r, echo = FALSE, results = "hide"}
include_supplement("eur-inferential_statistics-261-nl-data.sav", recursive = TRUE)
include_supplement("eur-inferential_statistics-261-nl-data.csv", recursive = TRUE)
```

Question
========
Toets of het gemiddelde cijfer op tentamen 6 (variabele vak6) voor uitwonende studenten [Woon = 0] significant afwijkt van het gemiddelde voor thuiswonende [Woon = 1] studenten. Schrijf de gevonden p-waarde in het antwoordvakje (met 3 cijfers achter de komma).

**Download**: [SPSS file](eur-inferential_statistics-260-nl-data.sav), [CSV file](eur-inferential_statistics-261-nl-data.csv)


Solution
========
Het correcte antwoord is 0.462.


Meta-information
================
exname: eur-inferential_statistics-261-nl
extype: num
exsolution: 0.462
extol: 0
exsection: Inferential Statistics/NHST/p-value, Inferential Statistics/Parametric Techniques/t-test/Independent samples means
exextra[Type]: Performing analysis
exextra[Program]: SPSS
exextra[Language]: Dutch
exextra[Level]: Statistical Literacy
